package cm.logram.lecitoyen.reglesDeDroits;

import android.annotation.SuppressLint;
import android.app.SearchManager;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.FloatingActionButton;
import android.support.v4.view.MenuItemCompat;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.SearchView;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

import cm.logram.lecitoyen.R;
import cm.logram.lecitoyen.adapter.AdapterCodeDeJusticeMilitaire.ClickListener;
import cm.logram.lecitoyen.adapter.AdapterCodePenale;
import cm.logram.lecitoyen.favoris.FavorisCodePenale;
import cm.logram.lecitoyen.model.Data;

@SuppressLint("NewApi")
public class CodePenale extends AppCompatActivity implements ClickListener,View.OnClickListener, SearchView.OnQueryTextListener {

  private Toolbar toolbar;
  private FloatingActionButton floatingActionButton;
  private RecyclerView mRecyclerView;
  private AdapterCodePenale mRecyclerAdapter;
  private List<Data> list;
  private SharedPreferences mSharedPreferences;
  private String searchString = "";
  private SearchView searchView;
  private TextView textView;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_code_penale);

    mSharedPreferences = getSharedPreferences("spWords", 0);

    toolbar = findViewById(R.id.toolbar);
    toolbar.setTitle("");
    setSupportActionBar(toolbar);

    textView = findViewById(R.id.en_tête);
    floatingActionButton = findViewById(R.id.fab);
    floatingActionButton.setOnClickListener(this);

    list = new ArrayList<>();
    mRecyclerView = findViewById(R.id.recyclerViewMain);
    mRecyclerAdapter = new AdapterCodePenale(getApplicationContext(), list);
    mRecyclerView.setHasFixedSize(true);
    mRecyclerAdapter.setListener(this);
    mRecyclerView.setItemAnimator(new DefaultItemAnimator());
    mRecyclerView.setLayoutManager(new LinearLayoutManager(getApplicationContext()));
    mRecyclerView.setAdapter(mRecyclerAdapter);

    /*Cache le bouton flottant lors du scroll*/
    mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
      @Override
      public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
        if (dy > 0 && floatingActionButton.isShown()) {
          floatingActionButton.hide();
        } else if (dy < 0 && floatingActionButton.getVisibility() != View.VISIBLE) {
          floatingActionButton.show();
        }
      }
    });
    prepareWordsList();
  }

  @Override
  public void onClick(View view) {
    switch (view.getId()) {
      case R.id.fab:
        Intent favList = new Intent(this, FavorisCodePenale.class);
        startActivity(favList);
        break;
    }
  }

  @Override
  public void itemClicked(View view, int position) {
  }

  private void prepareWordsList() {

    String titre1 = getText(R.string.titre1).toString();
    String titre2 = getText(R.string.titre2).toString();
    String titre3 = getText(R.string.titre3).toString();
    String titre4 = getText(R.string.titre4).toString();
    String titre5 = getText(R.string.titre5).toString();
    String titre6 = getText(R.string.titre6).toString();
    String titre7 = getText(R.string.titre7).toString();
    String titre8 = getText(R.string.titre8).toString();
    String titre9 = getText(R.string.titre9).toString();
    String titre10 = getText(R.string.titre10).toString();
    String titre11 = getText(R.string.titre11).toString();
    String titre12 = getText(R.string.titre12).toString();
    String titre13 = getText(R.string.titre13).toString();
    String titre14 = getText(R.string.titre14).toString();
    String titre15 = getText(R.string.titre15).toString();
    String titre16 = getText(R.string.titre16).toString();
    String titre17 = getText(R.string.titre17).toString();
    String titre18 = getText(R.string.titre18).toString();
    String titre19 = getText(R.string.titre19).toString();
    String titre20 = getText(R.string.titre20).toString();
    String titre21 = getText(R.string.titre21).toString();
    String titre22 = getText(R.string.titre22).toString();
    String titre23 = getText(R.string.titre23).toString();
    String titre24 = getText(R.string.titre24).toString();
    String titre25 = getText(R.string.titre25).toString();
    String titre26 = getText(R.string.titre26).toString();
    String titre27 = getText(R.string.titre27).toString();
    String titre28 = getText(R.string.titre28).toString();
    String titre29 = getText(R.string.titre29).toString();
    String titre30 = getText(R.string.titre30).toString();
    String titre31 = getText(R.string.titre31).toString();
    String titre32 = getText(R.string.titre32).toString();
    String titre33 = getText(R.string.titre33).toString();
    String titre34 = getText(R.string.titre34).toString();
    String titre35 = getText(R.string.titre35).toString();
    String titre36 = getText(R.string.titre36).toString();
    String titre37 = getText(R.string.titre37).toString();
    String titre38 = getText(R.string.titre38).toString();
    String titre39 = getText(R.string.titre39).toString();
    String titre40 = getText(R.string.titre40).toString();
    String titre41 = getText(R.string.titre41).toString();
    String titre42 = getText(R.string.titre42).toString();
    String titre43 = getText(R.string.titre43).toString();
    String titre44 = getText(R.string.titre44).toString();
    String titre45 = getText(R.string.titre45).toString();
    String titre46 = getText(R.string.titre46).toString();
    String titre47 = getText(R.string.titre47).toString();
    String titre48 = getText(R.string.titre48).toString();
    String titre49 = getText(R.string.titre49).toString();
    String titre50 = getText(R.string.titre50).toString();
    String titre51 = getText(R.string.titre51).toString();
    String titre52 = getText(R.string.titre52).toString();
    String titre53 = getText(R.string.titre53).toString();
    String titre54 = getText(R.string.titre54).toString();
    String titre55 = getText(R.string.titre55).toString();
    String titre56 = getText(R.string.titre56).toString();
    String titre57 = getText(R.string.titre57).toString();
    String titre58 = getText(R.string.titre58).toString();
    String titre59 = getText(R.string.titre59).toString();
    String titre60 = getText(R.string.titre60).toString();
    String titre61 = getText(R.string.titre61).toString();
    String titre62 = getText(R.string.titre62).toString();
    String titre63 = getText(R.string.titre63).toString();
    String titre64 = getText(R.string.titre64).toString();
    String titre65 = getText(R.string.titre65).toString();
    String titre66 = getText(R.string.titre66).toString();
    String titre67 = getText(R.string.titre67).toString();
    String titre68 = getText(R.string.titre68).toString();
    String titre69 = getText(R.string.titre69).toString();
    String titre70 = getText(R.string.titre70).toString();
    String titre71 = getText(R.string.titre71).toString();
    String titre72 = getText(R.string.titre72).toString();
    String titre73 = getText(R.string.titre73).toString();
    String titre74 = getText(R.string.titre74).toString();
    String titre75 = getText(R.string.titre75).toString();
    String titre76 = getText(R.string.titre76).toString();
    String titre77 = getText(R.string.titre77).toString();
    String titre78 = getText(R.string.titre78).toString();

    String article1 = getText(R.string.article1).toString();
    String article1_1 = getText(R.string.article1_1).toString();
    String article2 = getText(R.string.article2).toString();
    String article3 = getText(R.string.article3).toString();
    String article4 = getText(R.string.article4).toString();
    String article5 = getText(R.string.article5).toString();
    String article6 = getText(R.string.article6).toString();
    String article7 = getText(R.string.article7).toString();
    String article8 = getText(R.string.article8).toString();
    String article9 = getText(R.string.article9).toString();
    String article10 = getText(R.string.article10).toString();
    String article11 = getText(R.string.article11).toString();
    String article12 = getText(R.string.article12).toString();
    String article13 = getText(R.string.article13).toString();
    String article14 = getText(R.string.article14).toString();
    String article15 = getText(R.string.article15).toString();
    String article16 = getText(R.string.article16).toString();
    String article17 = getText(R.string.article17).toString();
    String article18 = getText(R.string.article18).toString();
    String article19 = getText(R.string.article19).toString();
    String article20 = getText(R.string.article20).toString();
    String article21 = getText(R.string.article21).toString();
    String article22 = getText(R.string.article22).toString();
    String article23 = getText(R.string.article23).toString();
    String article24 = getText(R.string.article24).toString();
    String article25 = getText(R.string.article25).toString();
    String article25_1 = getText(R.string.article25_1).toString();
    String article25_2 = getText(R.string.article25_2).toString();
    String article25_3 = getText(R.string.article25_3).toString();
    String article26 = getText(R.string.article26).toString();
    String article26_1 = getText(R.string.article26_1).toString();
    String article26_2 = getText(R.string.article26_2).toString();
    String article26_3 = getText(R.string.article26_3).toString();
    String article27 = getText(R.string.article27).toString();
    String article28 = getText(R.string.article28).toString();
    String article29 = getText(R.string.article29).toString();
    String article30 = getText(R.string.article30).toString();
    String article31 = getText(R.string.article31).toString();
    String article32 = getText(R.string.article32).toString();
    String article33 = getText(R.string.article33).toString();
    String article34 = getText(R.string.article34).toString();
    String article34_1 = getText(R.string.article34_1).toString();
    String article35 = getText(R.string.article35).toString();
    String article36 = getText(R.string.article36).toString();
    String article37 = getText(R.string.article37).toString();
    String article38 = getText(R.string.article38).toString();
    String article39 = getText(R.string.article39).toString();
    String article40 = getText(R.string.article40).toString();
    String article41 = getText(R.string.article41).toString();
    String article42 = getText(R.string.article42).toString();
    String article43 = getText(R.string.article43).toString();
    String article44 = getText(R.string.article44).toString();
    String article45 = getText(R.string.article45).toString();
    String article46 = getText(R.string.article46).toString();
    String  article47 = getText(R.string.article47).toString();
    String  article48 = getText(R.string.article48).toString();
    String article49 = getText(R.string.article49).toString();
    String article50 = getText(R.string.article50).toString();
    String article51 = getText(R.string.article51).toString();
    String article52 = getText(R.string.article52).toString();
    String article53 = getText(R.string.article53).toString();
    String article54 = getText(R.string.article54).toString();
    String article55 = getText(R.string.article55).toString();
    String article56 = getText(R.string.article56).toString();
    String article57 = getText(R.string.article57).toString();
    String article58 = getText(R.string.article58).toString();
    String article59 = getText(R.string.article59).toString();
    String article60 = getText(R.string.article60).toString();
    String article61 = getText(R.string.article61).toString();
    String article62 = getText(R.string.article62).toString();
    String article63 = getText(R.string.article63).toString();
    String article64 = getText(R.string.article64).toString();
    String article65 = getText(R.string.article65).toString();
     String article66 = getText(R.string.article66).toString();
    String article67 = getText(R.string.article67).toString();
    String article68 = getText(R.string.article68).toString();
    String article69 = getText(R.string.article69).toString();
    String article70 = getText(R.string.article70).toString();
    String article71 = getText(R.string.article71).toString();
    String article72 = getText(R.string.article72).toString();
    String article73 = getText(R.string.article73).toString();
    String article74 = getText(R.string.article74).toString();
    String article74_1 = getText(R.string.article74_1).toString();
    String article75 = getText(R.string.article75).toString();
    String article76 = getText(R.string.article76).toString();
    String article77 = getText(R.string.article77).toString();
    String article78 = getText(R.string.article78).toString();
    String article79 = getText(R.string.article79).toString();
    String article80 = getText(R.string.article80).toString();
    String article81 = getText(R.string.article81).toString();
    String article82 = getText(R.string.article82).toString();
    String article83 = getText(R.string.article83).toString();
    String article84 = getText(R.string.article84).toString();
    String article85 = getText(R.string.article85).toString();
    String article86 = getText(R.string.article86).toString();
    String article87 = getText(R.string.article87).toString();
    String article88 = getText(R.string.article88).toString();
    String article89 = getText(R.string.article89).toString();
    String article90 = getText(R.string.article90).toString();
    String article91 = getText(R.string.article91).toString();
    String article92 = getText(R.string.article92).toString();
    String article93 = getText(R.string.article93).toString();
    String article94 = getText(R.string.article94).toString();
    String article95 = getText(R.string.article95).toString();
    String article96 = getText(R.string.article96).toString();
    String article97 = getText(R.string.article97).toString();
    String article98 = getText(R.string.article98).toString();
    String article99 = getText(R.string.article99).toString();
    String article100 = getText(R.string.article100).toString();
    String article101 = getText(R.string.article101).toString();
    String article102 = getText(R.string.article102).toString();
    String article103 = getText(R.string.article103).toString();
    String article104 = getText(R.string.article104).toString();
    String article105 = getText(R.string.article105).toString();
    String article106 = getText(R.string.article106).toString();
    String article107 = getText(R.string.article107).toString();
    String article108 = getText(R.string.article108).toString();
    String article109 = getText(R.string.article109).toString();
    String article110 = getText(R.string.article110).toString();
    String article111 = getText(R.string.article111).toString();
    String article112 = getText(R.string.article112).toString();
    String article113 = getText(R.string.article113).toString();
    String  article114 = getText(R.string.article114).toString();
    String article115 = getText(R.string.article115).toString();
    String article116 = getText(R.string.article116).toString();
    String article117 = getText(R.string.article117).toString();
    String article118 = getText(R.string.article118).toString();
    String article119 = getText(R.string.article119).toString();
    String article120 = getText(R.string.article120).toString();
    String article121 = getText(R.string.article121).toString();
    String article122 = getText(R.string.article122).toString();
    String article123 = getText(R.string.article123).toString();
    String article123_1 = getText(R.string.article123_1).toString();
    String article123_2 = getText(R.string.article123_2).toString();
    String article123_3 = getText(R.string.article123_3).toString();
    String article123_4 = getText(R.string.article123_4).toString();
    String article124 = getText(R.string.article124).toString();
    String article125 = getText(R.string.article125).toString();
    String article126 = getText(R.string.article126).toString();
    String article127 = getText(R.string.article127).toString();
    String article128 = getText(R.string.article128).toString();
    String article129 = getText(R.string.article129).toString();
    String article130 = getText(R.string.article130).toString();
    String article131 = getText(R.string.article131).toString();
    String article131_1 = getText(R.string.article131_1).toString();
    String article132 = getText(R.string.article132).toString();
    String article133 = getText(R.string.article133).toString();
    String article134 = getText(R.string.article134).toString();
    String article134_1 = getText(R.string.article134_1).toString();
    String article134_2 = getText(R.string.article134_2).toString();
    String article135 = getText(R.string.article135).toString();
    String article135_1 = getText(R.string.article135_1).toString();
    String article135_2 = getText(R.string.article135_2).toString();
    String article136 = getText(R.string.article136).toString();
    String article136_1 = getText(R.string.article136_1).toString();
    String article137 = getText(R.string.article137).toString();
    String article138 = getText(R.string.article138).toString();
    String article139 = getText(R.string.article139).toString();
    String article140 = getText(R.string.article140).toString();
    String article141 = getText(R.string.article141).toString();
    String article142 = getText(R.string.article142).toString();
    String article143 = getText(R.string.article143).toString();
    String article144 = getText(R.string.article144).toString();
    String article145 = getText(R.string.article145).toString();
    String article146 = getText(R.string.article146).toString();
    String article147 = getText(R.string.article147).toString();
    String article148 = getText(R.string.article148).toString();
    String article149 = getText(R.string.article149).toString();
    String article150 = getText(R.string.article150).toString();
    String  article151 = getText(R.string.article151).toString();
    String article152 = getText(R.string.article152).toString();
    String article153 = getText(R.string.article153).toString();
    String article154 = getText(R.string.article154).toString();
    String article155 = getText(R.string.article155).toString();
    String article156 = getText(R.string.article156).toString();
    String article157 = getText(R.string.article157).toString();
    String  article158 = getText(R.string.article158).toString();
    String article159 = getText(R.string.article159).toString();
    String article160 = getText(R.string.article160).toString();
    String article161 = getText(R.string.article161).toString();
    String  article162 = getText(R.string.article162).toString();
    String article163 = getText(R.string.article163).toString();
    String article163_1 = getText(R.string.article163_1).toString();
    String article164 = getText(R.string.article164).toString();
    String article165 = getText(R.string.article165).toString();
    String article166 = getText(R.string.article166).toString();
    String article167 = getText(R.string.article167).toString();
    String article168 = getText(R.string.article168).toString();
    String article169 = getText(R.string.article169).toString();
    String article170 = getText(R.string.article170).toString();
    String  article171 = getText(R.string.article171).toString();
    String article172 = getText(R.string.article172).toString();
    String article173 = getText(R.string.article173).toString();
    String article174 = getText(R.string.article174).toString();
    String article175 = getText(R.string.article175).toString();
    String article176 = getText(R.string.article176).toString();
    String article177 = getText(R.string.article177).toString();
    String article178 = getText(R.string.article178).toString();
    String article179 = getText(R.string.article179).toString();
    String article180 = getText(R.string.article180).toString();
    String article180_1 = getText(R.string.article180_1).toString();
    String article181 = getText(R.string.article181).toString();
    String article181_1 = getText(R.string.article181_1).toString();
    String  article182 = getText(R.string.article182).toString();
    String article183 = getText(R.string.article183).toString();
    String article184 = getText(R.string.article184).toString();
    String article185 = getText(R.string.article185).toString();
    String article186 = getText(R.string.article186).toString();
    String article187 = getText(R.string.article187).toString();
    String article187_1 = getText(R.string.article187_1).toString();
    String article188 = getText(R.string.article188).toString();
    String article188_1 = getText(R.string.article188_1).toString();
    String article188_2 = getText(R.string.article188_2).toString();
    String article189 = getText(R.string.article189).toString();
    String article190 = getText(R.string.article190).toString();
    String article191 = getText(R.string.article191).toString();
    String article192 = getText(R.string.article192).toString();
    String article193 = getText(R.string.article193).toString();
    String article194 = getText(R.string.article194).toString();
    String article195 = getText(R.string.article195).toString();
    String article196 = getText(R.string.article196).toString();
    String article197 = getText(R.string.article197).toString();
    String article198 = getText(R.string.article198).toString();
    String article199 = getText(R.string.article199).toString();
    String article200 = getText(R.string.article200).toString();
    String article201 = getText(R.string.article201).toString();
    String article201_1 = getText(R.string.article201_1).toString();
    String article202 = getText(R.string.article202).toString();
    String article203 = getText(R.string.article203).toString();
    String article204 = getText(R.string.article204).toString();
    String article205 = getText(R.string.article205).toString();
    String article206 = getText(R.string.article206).toString();
    String article207 = getText(R.string.article207).toString();
    String article208 = getText(R.string.article208).toString();
    String article209 = getText(R.string.article209).toString();
    String article210 = getText(R.string.article210).toString();
    String article211 = getText(R.string.article211).toString();
    String article212 = getText(R.string.article212).toString();
    String article213 = getText(R.string.article213).toString();
    String article214 = getText(R.string.article214).toString();
    String article215 = getText(R.string.article215).toString();
    String article216 = getText(R.string.article216).toString();
    String article217 = getText(R.string.article217).toString();
    String article218 = getText(R.string.article218).toString();
    String article219 = getText(R.string.article219).toString();
    String article219_1 = getText(R.string.article219_1).toString();
    String article220 = getText(R.string.article220).toString();
    String article221 = getText(R.string.article221).toString();
    String article222 = getText(R.string.article222).toString();
    String article223 = getText(R.string.article223).toString();
    String article224 = getText(R.string.article224).toString();
    String article225 = getText(R.string.article225).toString();
    String article226 = getText(R.string.article226).toString();
    String article227 = getText(R.string.article227).toString();
    String article228 = getText(R.string.article228).toString();
    String article229 = getText(R.string.article229).toString();
    String article229_1 = getText(R.string.article229_1).toString();
    String article230 = getText(R.string.article230).toString();
    String article231 = getText(R.string.article231).toString();
    String article231_1 = getText(R.string.article231_1).toString();
    String article232 = getText(R.string.article232).toString();
    String article233 = getText(R.string.article233).toString();
    String article234 = getText(R.string.article234).toString();
    String article235 = getText(R.string.article235).toString();
    String article236 = getText(R.string.article236).toString();
    String article237 = getText(R.string.article237).toString();
    String article238 = getText(R.string.article238).toString();
    String article239 = getText(R.string.article239).toString();
    String article240 = getText(R.string.article240).toString();
    String article241 = getText(R.string.article241).toString();
    String article242 = getText(R.string.article242).toString();
    String article243 = getText(R.string.article243).toString();
    String article244 = getText(R.string.article244).toString();
    String article245 = getText(R.string.article245).toString();
    String article246 = getText(R.string.article246).toString();
    String article247 = getText(R.string.article247).toString();
    String article248 = getText(R.string.article248).toString();
    String article249 = getText(R.string.article249).toString();
    String article249_1 = getText(R.string.article249_1).toString();
    String article249_2 = getText(R.string.article249_2).toString();
    String article249_3 = getText(R.string.article249_3).toString();
    String article249_4 = getText(R.string.article249_4).toString();
    String article249_5 = getText(R.string.article249_5).toString();
    String article249_6 = getText(R.string.article249_6).toString();
    String article249_7 = getText(R.string.article249_7).toString();
    String article249_8 = getText(R.string.article249_8).toString();
    String article249_9 = getText(R.string.article249_9).toString();
    String article250 = getText(R.string.article250).toString();
    String article251 = getText(R.string.article251).toString();
    String article252 = getText(R.string.article252).toString();
    String article253 = getText(R.string.article253).toString();
    String article254 = getText(R.string.article254).toString();
    String article255 = getText(R.string.article255).toString();
    String article256 = getText(R.string.article256).toString();
    String article257 = getText(R.string.article257).toString();
    String article258 = getText(R.string.article258).toString();
    String article258_1 = getText(R.string.article258).toString();
    String article259 = getText(R.string.article258_1).toString();
    String article260 = getText(R.string.article259).toString();
    String article261 = getText(R.string.article261).toString();
    String article262 = getText(R.string.article262).toString();
    String article263 = getText(R.string.article263).toString();
    String article264 = getText(R.string.article264).toString();
    String article265 = getText(R.string.article265).toString();
    String article266 = getText(R.string.article266).toString();
    String article267 = getText(R.string.article267).toString();
    String article268 = getText(R.string.article268).toString();
    String article268_1 = getText(R.string.article268_1).toString();
    String article269 = getText(R.string.article269).toString();
    String article270 = getText(R.string.article270).toString();
    String article271 = getText(R.string.article271).toString();
    String article272 = getText(R.string.article272).toString();
    String article273 = getText(R.string.article273).toString();
    String article274 = getText(R.string.article274).toString();
    String article275 = getText(R.string.article275).toString();
    String article276 = getText(R.string.article276).toString();
    String article277 = getText(R.string.article277).toString();
    String article277_1 = getText(R.string.article277_1).toString();
    String article277_2 = getText(R.string.article277_2).toString();
    String article277_3 = getText(R.string.article277_3).toString();
    String article278 = getText(R.string.article278).toString();
    String article279 = getText(R.string.article279).toString();
    String article280 = getText(R.string.article280).toString();
    String article281 = getText(R.string.article281).toString();
    String article282 = getText(R.string.article282).toString();
    String article283 = getText(R.string.article283).toString();
    String article284 = getText(R.string.article284).toString();
    String article285 = getText(R.string.article285).toString();
    String article286 = getText(R.string.article286).toString();
    String article287 = getText(R.string.article287).toString();
    String article288 = getText(R.string.article288).toString();
    String article289 = getText(R.string.article289).toString();
    String article290 = getText(R.string.article290).toString();
    String article291 = getText(R.string.article291).toString();
    String article292 = getText(R.string.article292).toString();
    String  article293 = getText(R.string.article293).toString();
    String article294 = getText(R.string.article294).toString();
    String article295 = getText(R.string.article295).toString();
    String article296 = getText(R.string.article296).toString();
    String article297 = getText(R.string.article297).toString();
    String article298 = getText(R.string.article298).toString();
    String article299 = getText(R.string.article299).toString();
    String article300 = getText(R.string.article300).toString();
    String article301 = getText(R.string.article301).toString();
    String article302 = getText(R.string.article302).toString();
    String article302_1 = getText(R.string.article302_1).toString();
    String article303 = getText(R.string.article303).toString();
    String article304 = getText(R.string.article304).toString();
    String article305 = getText(R.string.article305).toString();
    String article306 = getText(R.string.article306).toString();
    String article307 = getText(R.string.article307).toString();
    String article308 = getText(R.string.article308).toString();
    String  article309 = getText(R.string.article309).toString();
    String  article310 = getText(R.string.article310).toString();
    String article311 = getText(R.string.article311).toString();
    String article311_1 = getText(R.string.article311_1).toString();
    String article311_2 = getText(R.string.article311_2).toString();
    String article311_3 = getText(R.string.article311_3).toString();
    String article312 = getText(R.string.article312).toString();
    String article313 = getText(R.string.article313).toString();
    String article313_1 = getText(R.string.article313_1).toString();
    String article314 = getText(R.string.article314).toString();
    String article314_1 = getText(R.string.article314_1).toString();
    String article315 = getText(R.string.article315).toString();
    String article316 = getText(R.string.article316).toString();
    String article317 = getText(R.string.article317).toString();
    String article318 = getText(R.string.article318).toString();
    String article319 = getText(R.string.article319).toString();
    String article320 = getText(R.string.article320).toString();
    String article321 = getText(R.string.article321).toString();
    String article322 = getText(R.string.article322).toString();
    String article322_1 = getText(R.string.article322_1).toString();
    String article322_2 = getText(R.string.article322_2).toString();
    String article322_3 = getText(R.string.article322_3).toString();
    String article323 = getText(R.string.article323).toString();
    String article324 = getText(R.string.article324).toString();
    String article325 = getText(R.string.article325).toString();
    String article326 = getText(R.string.article326).toString();
    String article327 = getText(R.string.article327).toString();
    String article328 = getText(R.string.article328).toString();
    String article329 = getText(R.string.article329).toString();
    String article330 = getText(R.string.article330).toString();
    String article331 = getText(R.string.article331).toString();
    String article332 = getText(R.string.article332).toString();
    String article333 = getText(R.string.article333).toString();
    String article334 = getText(R.string.article334).toString();
    String article334_1 = getText(R.string.article334_1).toString();
    String article334_2 = getText(R.string.article334_2).toString();
    String article335 = getText(R.string.article335).toString();
    String article335_1 = getText(R.string.article335_1).toString();
    String article335_2 = getText(R.string.article335_2).toString();
    String article335_3 = getText(R.string.article335_3).toString();
    String article336 = getText(R.string.article336).toString();
    String article337 = getText(R.string.article337).toString();
    String article338 = getText(R.string.article338).toString();
    String article339 = getText(R.string.article339).toString();
    String article340 = getText(R.string.article340).toString();
    String article341 = getText(R.string.article341).toString();
    String article342 = getText(R.string.article342).toString();
    String article342_1 = getText(R.string.article342_1).toString();
    String article343 = getText(R.string.article343).toString();
    String article344 = getText(R.string.article344).toString();
    String article345 = getText(R.string.article345).toString();
    String article346 = getText(R.string.article346).toString();
    String article347 = getText(R.string.article347).toString();
    String article347_1 = getText(R.string.article347_1).toString();
    String article348 = getText(R.string.article348).toString();
    String article349 = getText(R.string.article349).toString();
    String article350 = getText(R.string.article350).toString();
    String article351 = getText(R.string.article351).toString();
    String article352 = getText(R.string.article352).toString();
    String article353 = getText(R.string.article353).toString();
    String article354 = getText(R.string.article354).toString();
    String article355 = getText(R.string.article355).toString();
    String article355_1 = getText(R.string.article355_1).toString();
    String article355_2 = getText(R.string.article355_2).toString();
    String article356 = getText(R.string.article356).toString();
    String article357 = getText(R.string.article357).toString();
    String article358 = getText(R.string.article358).toString();
    String article358_1 = getText(R.string.article358_1).toString();
    String article359 = getText(R.string.article359).toString();
    String article360 = getText(R.string.article360).toString();
    String article361 = getText(R.string.article361).toString();
    String article362 = getText(R.string.article362_a_370).toString();
    String article371 = getText(R.string.article371).toString();
    String article372 = getText(R.string.article372).toString();

    Data data = new Data(titre1, "Article 1", article1);
    list.add(data);
    data = new Data("", "Article 1-1. - Aucune Exemption", article1_1);
    list.add(data);
    data = new Data("", "le 2. - Application generale et speciale", article2);
    list.add(data);
    data = new Data(titre2, "Article 3. -Non RétroActivité", article3);
    list.add(data);
    data = new Data("", "Article 4. - Loi Moins Rigoureuse", article4);
    list.add(data);
    data = new Data("", "Article 5. - Nouvelle mesure de sûrete", article5);
    list.add(data);
    data = new Data("", "Article 6. - Abolition de L'infraction, de la peine ou de la mesure de sûreté", article6);
    list.add(data);
    data = new Data(titre3, "Article 7. - Infraction commise sur le territoire", article7);
    list.add(data);
    data = new Data("", "Article 8. - Infraction partiellement ou totalement commise a l'étranger", article8);
    list.add(data);
    data = new Data("", "Article 9. - Complicité, conspiration, tentative", article9);
    list.add(data);
    data = new Data("", "Article 10. - Infraction commise à l'étranger par le citoyen ou résident", article10);
    list.add(data);
    data = new Data("", "Article 11. - Infractions internationales", article11);
    list.add(data);
    data = new Data("", "Article 12. -Competence generale des juridictions de la Republique", article12);
    list.add(data);
    data = new Data(titre4, "Article 13. - Exclusion de la loi etrangère", article13);
    list.add(data);
    data = new Data("", "Article 14. - Sentences étrangères", article14);
    list.add(data);
    data = new Data("", "Article 15. - Effets des sentences étrangères", article15);
    list.add(data);
    data = new Data("", "Article 16. - Execution des sentences étrangères", article16);
    list.add(data);
    data = new Data(titre5, "Article 17. - Légalite des peines et des infractions", article17);
    list.add(data);
    data = new Data("", "Article 18. - Peines principales", article18);
    list.add(data);
    data = new Data("", "Article 19. - Peines accessoires", article19);
    list.add(data);
    data = new Data("", "Article 20. - Mesures de sûreté", article20);
    list.add(data);
    data = new Data("", "Article 21. - Classification des infractions", article21);
    list.add(data);
    data = new Data(titre6, "Article 22. - Conditions préalables a l'exécution", article22);
    list.add(data);
    data = new Data("", "Article 23. - Exécution", article23);
    list.add(data);
    data = new Data(titre7, "Article 24. - Emprisonnement", article24);
    list.add(data);
    data = new Data("", "Article 25.- Pécule", article25);
    list.add(data);
    data = new Data(titre8, "Article 25-1. - Amende", article25_1);
    list.add(data);
    data = new Data(titre9, "Article 25-2. - Dissolution", article25_2);
    list.add(data);
    data = new Data(titre10, "Article 25-3. - Fermeture de l'établissement", article25_3);
    list.add(data);
    data = new Data(titre11, "Article 26. - Travail d'intérêt général", article26);
    list.add(data);
    data = new Data("", "Article 26-1. - Sanction-reparation", article26_1);
    list.add(data);
    data = new Data("", "Article 26-2. - Mise en œuvre des peines alternatives", article26_2);
    list.add(data);
    data = new Data("", "Article 26-3. - Personnes exclues du bénéfice des peines alternatives", article26_3);
    list.add(data);
    data = new Data(titre12, "Article 27. - Debut de la peine", article27);
    list.add(data);
    data = new Data("", "Article 28. - Calcul de la peine", article28);
    list.add(data);
    data = new Data("", "Article 29. - Séparation des mineurs", article29);
    list.add(data);
    data = new Data(titre13, "Article 30. - Définition", article30);
    list.add(data);
    data = new Data("", "Article 31. - Application", article31);
    list.add(data);
    data = new Data("", "Article 32. - Déchéances et condamnation par défaut", article32);
    list.add(data);
    data = new Data(titre14, "Article 33. - Publication de la decision", article33);
    list.add(data);
    data = new Data("", "Article 34. - Fermeture de l'etablissement", article34);
    list.add(data);
    data = new Data("", "Article 34-1. - Placement sous surveillance judiciaire", article34_1);
    list.add(data);
    data = new Data("", "Article 35. - Confiscation du «corpus delicti»", article35);
    list.add(data);
    data = new Data(titre15, "Article 36. - Interdiction de la profession", article36);
    list.add(data);
    data = new Data(titre16, "Article 37. - Definition de la relegation", article37);
    list.add(data);
    data = new Data("", "Article 38. - Personnes exclues de la relégation", article38);
    list.add(data);
    data = new Data("", "Article 39. - Conditions de la relégation", article39);
    list.add(data);
    data = new Data(titre17, "Article 40. - Définition et durée", article40);
    list.add(data);
    data = new Data("", "Article 41. - Obligations générales", article41);
    list.add(data);
    data = new Data("", "Article 42. - Obligations spéciales", article42);
    list.add(data);
    data = new Data(titre18, "Article 43. - Malade mental", article43);
    list.add(data);
    data = new Data("", "Article 44. - Infirmité mentale", article44);
    list.add(data);
    data = new Data(titre19, "Article 45. - Confiscuation", article45);
    list.add(data);
    data = new Data(titre20, "Article 46. - Conditions", article46);
    list.add(data);
    data = new Data("", "Article 47. - Durées", article47);
    list.add(data);
    data = new Data("", "Article 48. - Engagement des parents ou du tuteur", article48);
    list.add(data);
    data = new Data("", "Article 49. - Refus de l'engagement", article49);
    list.add(data);
    data = new Data("", "Article 50. - Inobservation", article50);
    list.add(data);
    data = new Data(titre21, "Article 51. - Non-cumul", article51);
    list.add(data);
    data = new Data("", "Article 52. - Ordre d'exécution", article52);
    list.add(data);
    data = new Data("", "Article 53. - Detention provisoire", article53);
    list.add(data);
    data = new Data(titre22, "Article 54. - Conditions d'application et effets", article54);
    list.add(data);
    data = new Data(titre23, "Article 55. - Conditions d'application", article55);
    list.add(data);
    data = new Data("", "Article 56. - Le régime de probation", article56);
    list.add(data);
    data = new Data("", "Article 57. - Obligations générales", article57);
    list.add(data);
    data = new Data("", "Article 58. - Obligations spéciales", article58);
    list.add(data);
    data = new Data("", "Article 59. - Obligation du délégué", article59);
    list.add(data);
    data = new Data("", "Article 60. - Violation des obligations", article60);
    list.add(data);
    data = new Data(titre24, "Article 61. - Définition", article61);
    list.add(data);
    data = new Data("", "Article 62. - Suspension des mesures", article62);
    list.add(data);
    data = new Data("", "Article 63. - Délai pour l'octroi", article63);
    list.add(data);
    data = new Data("", "Article 64. - Révocation", article64);
    list.add(data);
    data = new Data(titre25, "Article 65. - Suspension des mesures post-penale", article65);
    list.add(data);
    data = new Data(titre26, "Article 66. - Grâce", article66);
    list.add(data);
    data = new Data("", "Article 67. - Prescription", article67);
    list.add(data);
    data = new Data("", "Article 68. - Mort", article68);
    list.add(data);
    data = new Data(titre27, "Article 69. - Définition des effets", article69);
    list.add(data);
    data = new Data("", "Article 70. - Réhabilitation de plein droit", article70);
    list.add(data);
    data = new Data("", "Article 71. - Réhabilitation judiciaire", article71);
    list.add(data);
    data = new Data("", "Article 72. - Réhabilitation post-mortem", article72);
    list.add(data);
    data = new Data(titre28, "Article 73. - Effets", article73);
    list.add(data);
    data = new Data(titre29, "Article 74. - Peine et responsabilité", article74);
    list.add(data);
    data = new Data("", "Article 74-1. - Personnes morales pénalement responsables", article74_1);
    list.add(data);
    data = new Data("", "Article 75. - Ignorance et mobile", article75);
    list.add(data);
    data = new Data("", "Article 76. - Exécution de la loi", article76);
    list.add(data);
    data = new Data(titre30, "Article 77. - Cas fortuit et contrainte materielle", article77);
    list.add(data);
    data = new Data("", "Article 78. - Démence", article78);
    list.add(data);
    data = new Data("", "Article 79. - Intoxication", article79);
    list.add(data);
    data = new Data("", "Article 80. - Minorité", article80);
    list.add(data);
    data = new Data("", "Article 81. - Ménaces", article81);
    list.add(data);
    data = new Data("", "Article 82. - Crainte réverencielle", article82);
    list.add(data);
    data = new Data("", "Article 83. - Obéissance a l'autorite légale", article83);
    list.add(data);
    data = new Data("", "Article 84. - Legitime défense", article84);
    list.add(data);
    data = new Data("", "Article 85. - Provocation", article85);
    list.add(data);
    data = new Data("", "Article 86. - Etat de necessité", article86);
    list.add(data);
    data = new Data("", "Article 87. - Effets de l'excuse attenuante", article87);
    list.add(data);
    data = new Data(titre31, "Article 88. - Recidive des personnes physiques et morales", article88);
    list.add(data);
    data = new Data("", "Article 89. - Fonctionnaires", article89);
    list.add(data);
    data = new Data(titre32, "Article 90. - Circonstances atténuantes", article90);
    list.add(data);
    data = new Data("", "Article 91. - Effets en cas de crime", article91);
    list.add(data);
    data = new Data("", "Article 92. - Effets en cas de délit ou de contravention", article92);
    list.add(data);
    data = new Data("", "Article 93. - Choix de la peine", article93);
    list.add(data);
    data = new Data(titre33, "Article 94. - Tentative", article94);
    list.add(data);
    data = new Data("", "Article 95. - Conspiration", article95);
    list.add(data);
    data = new Data(titre34, "Article 96. - Coaction", article96);
    list.add(data);
    data = new Data("", "Article 97. - Complicité", article97);
    list.add(data);
    data = new Data("", "Article 98. Peines", article98);
    list.add(data);
    data = new Data("", "Article 99. - Responsabilite pour les consequences previsibles", article99);
    list.add(data);
    data = new Data("", "Article 100. - Recel", article100);
    list.add(data);
    data = new Data(titre35, "Article 101. - Infractions aux textes des ex-Etats fédérés", article101);
    list.add(data);
    data = new Data(titre36, "Article 102. - Hostilités contre la patrie", article102);
    list.add(data);
    data = new Data("", "Article 103. - Autres crimes punis de mort", article103);
    list.add(data);
    data = new Data("", "Article 104. - Peines de drolt commun", article104);
    list.add(data);
    data = new Data("", "Article 105. - Atteintes punies d'un maximum de dix an", article105);
    list.add(data);
    data = new Data("", "Article 106. - Atteintes punies d'un maximum de cinq ans", article106);
    list.add(data);
    data = new Data("", "Article 107. - Non-dénonciation", article107);
    list.add(data);
    data = new Data("", "Article 108. - Temps de guerre", article108);
    list.add(data);
    data = new Data("", "Article 109. - Définition du secret de la défense nationale", article109);
    list.add(data);
    data = new Data("", "Article 110. - Extension aux puissances etrangères", article110);
    list.add(data);
    data = new Data(titre37, "Article 111. - Cessession", article111);
    list.add(data);
    data = new Data("", "Article 112. - Guerre civil", article112);
    list.add(data);
    data = new Data("", "Article 113. - Propagation de fausses nouvelles", article113);
    list.add(data);
    data = new Data("", "Article 114. - Revolution", article114);
    list.add(data);
    data = new Data("", "Article 115. - Bande armée", article115);
    list.add(data);
    data = new Data("", "Article 116. - Insurection", article116);
    list.add(data);
    data = new Data("", "Article 117. - Definition des armes", article117);
    list.add(data);
    data = new Data(titre38, "Article 118. - Confiscation spéciale", article118);
    list.add(data);
    data = new Data("", "Article 119. - Confiscation des biens illégitimes", article119);
    list.add(data);
    data = new Data("", "Article 120. - Confiscation générale", article120);
    list.add(data);
    data = new Data("", "Article 121. - Déchéances", article121);
    list.add(data);
    data = new Data(titre39, "Article 122. - Fraudes électorales", article122);
    list.add(data);
    data = new Data("", "Article 123. - Corruption et violences en matière électorale", article123);
    list.add(data);
    data = new Data("", "Article 123-1. - Port d'arme en periode electorale", article123_1);
    list.add(data);
    data = new Data("", "Article 123-2. - Activite ou manifestation a caractère politique en periode électorale", article123_2);
    list.add(data);
    data = new Data("", "Article 123-3. - Detournement de fonds publics en matière électorale", article123_3);
    list.add(data);
    data = new Data("", "Article 123-4. - Poursuites pénales en matière électorale", article123_4);
    list.add(data);
    data = new Data(titre40, "Article 124. - Coalition contre les lois, le fonctionnement d'un service et la sûrete de l'Etat", article124);
    list.add(data);
    data = new Data(titre41, "Article 125. - Empietements sur le pouvoir législatif", article125);
    list.add(data);
    data = new Data("", "Article 126. - Empietements sur le pouvoir executif et sur le pouvoir judiciaire", article126);
    list.add(data);
    data = new Data("", "Article 127. - Empletements du judiciaire sur certaines immunites", article127);
    list.add(data);
    data = new Data(titre42, "Article 128. - Emploi illegal de la force", article128);
    list.add(data);
    data = new Data("", "Article 129. - Inexécution des requisition", article129);
    list.add(data);
    data = new Data(titre43, "Article 130. - Déchéances", article130);
    list.add(data);
    data = new Data(titre44, "Article 131. - Definition du fonctionnaire", article131);
    list.add(data);
    data = new Data("", "Article 131-1. - Agent public étranger ou international", article131_1);
    list.add(data);
    data = new Data("", "Article 132. - Aggravation pour les fonctionnaires", article132);
    list.add(data);
    data = new Data("", "Article 133. - Déchéances, confiscation et publicité", article133);
    list.add(data);
    data = new Data(titre45, "Article 134. - Corruption active", article134);
    list.add(data);
    data = new Data("", "Article 134-1. - Corruption passive", article134_1);
    list.add(data);
    data = new Data("", "Article 134-2. - Exemption des poursuites", article134_2);
    list.add(data);
    data = new Data("", "Article 135. - Interêt dans un acte", article135);
    list.add(data);
    data = new Data("", "Article 135-1. - Délit d'initié", article135_1);
    list.add(data);
    data = new Data("", "Article 135-2. - Entraves au fonctionnement du marché financier", article135_2);
    list.add(data);
    data = new Data("", "Article 136. - Participation dans une affaire", article136);
    list.add(data);
    data = new Data("", "Article 136-1. - Prise d'emploi prohibée", article136_1);
    list.add(data);
    data = new Data(titre46, "Article 137. - Concussion au détriment de l'Etat", article137);
    list.add(data);
    data = new Data("", "Article 138. - Déficit non signalé", article138);
    list.add(data);
    data = new Data("", "Article 139. - Négligence du gardien", article139);
    list.add(data);
    data = new Data(titre47, "Article 140. - Abus de fonctions", article140);
    list.add(data);
    data = new Data("", "Article 141. - Atteinte aux droits civiques", article141);
    list.add(data);
    data = new Data("", "Article 142. - Concussion au detriment des particuliers", article142);
    list.add(data);
    data = new Data("", "Article 143. - Favoritisme", article143);
    list.add(data);
    data = new Data("", "Article 144. - Faux dans un acte", article144);
    list.add(data);
    data = new Data(titre48, "Article 145. - Tolérance d'un attroupemen", article145);
    list.add(data);
    data = new Data("", "Article 146. - Tolérance d'une atteinte aux droits individuels", article146);
    list.add(data);
    data = new Data("", "Article 147. - Deni de justice", article147);
    list.add(data);
    data = new Data("", "Article 148. - Refus d'un service dû", article148);
    list.add(data);
    data = new Data("", "Article 149. - Inobservation des formalites du mariage", article149);
    list.add(data);
    data = new Data("", "Article 150. - Tenue irréguliere des régistres d'etat civil", article150);
    list.add(data);
    data = new Data("", "Article 151. - Négligence systématique", article151);
    list.add(data);
    data = new Data(titre49, "Article 152. - Définition de l'outrage", article152);
    list.add(data);
    data = new Data("", "Article 153. - Outrage au Président de la République", article153);
    list.add(data);
    data = new Data("", "Article 154. - Outrage aux corps constitues et aux fonctionnaires", article154);
    list.add(data);
    data = new Data("", "Article 155. - Non publicité", article155);
    list.add(data);
    data = new Data("", "Article 156. - Violence a fonctionnaire", article156);
    list.add(data);
    data = new Data(titre50, "Article 157. - Rébélion", article157);
    list.add(data);
    data = new Data("", "Article 158. - Rébélion en groupe", article158);
    list.add(data);
    data = new Data("", "Article 159. - Caractère politique (Abrogé)", article159);
    list.add(data);
    data = new Data(titre51, "Article 160. - Contrainte de fonctionnaire", article160);
    list.add(data);
    data = new Data("", "Article 161. - Trafic d'influence", article161);
    list.add(data);
    data = new Data("", "Article 162. - Déclarations mensongères", article162);
    list.add(data);
    data = new Data("", "Article 163. - Fraude aux examens", article163);
    list.add(data);
    data = new Data("", "Article 163-1. - Corruption en matière de concours administratifs", article163_1);
    list.add(data);
    data = new Data(titre52, "Article 164. - Faux témoignage", article164);
    list.add(data);
    data = new Data("", "Article 165. - Fausse expertise", article165);
    list.add(data);
    data = new Data("", "Article 166. - Faux serment", article166);
    list.add(data);
    data = new Data("", "Article 167. - Dissimulation d'une procédure", article167);
    list.add(data);
    data = new Data("", "Article 168. - Suppression et fabrication de preuves", article168);
    list.add(data);
    data = new Data("", "Article 169. - Commentaires tendancieux", article169);
    list.add(data);
    data = new Data("", "Article 170. - Déchéances", article170);
    list.add(data);
    data = new Data(titre53, "Article 171. - Non intervention", article171);
    list.add(data);
    data = new Data("", "Article 172. - Refus d'innocenter", article172);
    list.add(data);
    data = new Data("", "Article 173. - Témoin défaillant", article173);
    list.add(data);
    data = new Data("", "Article 174. - Réquiq défaillant", article174);
    list.add(data);
    data = new Data("", "Article 175. - Assesseur ou Jure défaillant", article175);
    list.add(data);
    data = new Data("", "Article 176. - Fausses excuses", article176);
    list.add(data);
    data = new Data(titre54, "Article 177. - Interdiction de résidence", article177);
    list.add(data);
    data = new Data("", "Article 178. - Autres peines et mesures", article178);
    list.add(data);
    data = new Data("", "Article 179. - Garde d'un mineur", article179);
    list.add(data);
    data = new Data("", "Article 180. - Pension alimentaire", article180);
    list.add(data);
    data = new Data("", "Article 180-1. - Pension de réversion", article180_1);
    list.add(data);
    data = new Data("", "Article 181. - Insolvabilité organisée", article181);
    list.add(data);
    data = new Data("", "Article 181-1. - Refus d'executer une décision de justice devenue définitive", article181_1);
    list.add(data);
    data = new Data("", "Article 182. - Reprise d'un immeuble", article182);
    list.add(data);
    data = new Data(titre55, "Article 183. - Refus de l'impôt", article183);
    list.add(data);
    data = new Data("", "Article 184. - Détournement de biens publics", article184);
    list.add(data);
    data = new Data("", "Article 185. - Troubles dans le service", article185);
    list.add(data);
    data = new Data("", "Article 186. - Opposition a travaux", article186);
    list.add(data);
    data = new Data("", "Article 187. - Dégradation de biens publics ou classes", article187);
    list.add(data);
    data = new Data("", "Article 187-1. - Atteintes au patrimoine culturel et naturel national", article187_1);
    list.add(data);
    data = new Data("", "Article 188. - Soustraction et destruction de pieces publiques", article188);
    list.add(data);
    data = new Data("", "Article 188-1. - Soustraction et detournement de documents d'archives publiques ou privées", article188_1);
    list.add(data);
    data = new Data("", "Article 188-2. - Destruction, aliénation et exportation illicite des documents d'archives publiques", article188_2);
    list.add(data);
    data = new Data("", "Article 189. - Copie de document administratifs", article189);
    list.add(data);
    data = new Data("", "Article 190. - Détournement de biens saisis", article190);
    list.add(data);
    data = new Data("", "Article 191. - Bris de scelles", article191);
    list.add(data);
    data = new Data("", "Article 192. - Communications avec les détenus", article192);
    list.add(data);
    data = new Data("", "Article 193. - Evasion", article193);
    list.add(data);
    data = new Data("", "Article 194. - Recel d'individu", article194);
    list.add(data);
    data = new Data("", "Article 195. - Souscription pour amendes", article195);
    list.add(data);
    data = new Data("", "Article 196. - Lacération d'affiches", article196);
    list.add(data);
    data = new Data("", "Article 197. - Outrage ou dommage à témoin", article197);
    list.add(data);
    data = new Data("", "Article 198. - Publication interdite", article198);
    list.add(data);
    data = new Data("", "Article 199. - Registre des logeurs", article199);
    list.add(data);
    data = new Data("", "Article 200. - Inhumation irréguliere", article200);
    list.add(data);
    data = new Data(titre56, "Article 201. - Sceau de l'Etat", article201);
    list.add(data);
    data = new Data("", "Article 201-1. - Autres sceaux publics", article201_1);
    list.add(data);
    data = new Data("", "Article 202. - Effets du Trésor", article202);
    list.add(data);
    data = new Data("", "Article 203. - Signatures, timbres et poinçons", article203);
    list.add(data);
    data = new Data("", "Article 204. - Marques et imprimés", article204);
    list.add(data);
    data = new Data("", "Article 205. - Ecritures publiques et authentiques", article205);
    list.add(data);
    data = new Data("", "Article 206. - Documents et permis", article206);
    list.add(data);
    data = new Data("", "Article 207. - Certificats officiels", article207);
    list.add(data);
    data = new Data("", "Article 208. - Timbres -poste et fiscaux", article208);
    list.add(data);
    data = new Data("", "Article 209. - Documents postaux", article209);
    list.add(data);
    data = new Data("", "Article 210. - Immitations", article210);
    list.add(data);
    data = new Data("", "Article 211. - Fausse monaie", article211);
    list.add(data);
    data = new Data("", "Article 212. - Instruments de contrefaçon", article212);
    list.add(data);
    data = new Data("", "Article 213. - Détention irregulière", article213);
    list.add(data);
    data = new Data("", "Article 214. - Peines accessoires", article214);
    list.add(data);
    data = new Data(titre57, "Article 215. - Fabrication d'une monnaie", article215);
    list.add(data);
    data = new Data("", "Article 216. - Usurpation de fonctions", article216);
    list.add(data);
    data = new Data("", "Article 217. - Célébration du mariage", article217);
    list.add(data);
    data = new Data("", "Article 218. - Usurpation d'uniforme et de decoration", article218);
    list.add(data);
    data = new Data("", "Article 219-1. - Usurpation d'un titre", article219);
    list.add(data);
    data = new Data("", "Article 219-1. - Usurpation de denomination", article219_1);
    list.add(data);
    data = new Data("", "Article 220. - Titre honorifique", article220);
    list.add(data);
    data = new Data("", "Article 221. - Dispositions communes", article221);
    list.add(data);
    data = new Data(titre58, "Article 222. - Atteinte au credit de l'Etat", article222);
    list.add(data);
    data = new Data("", "Article 223. - Refus de la monnaie", article223);
    list.add(data);
    data = new Data("", "Article 224. - Atteinte au développement national", article224);
    list.add(data);
    data = new Data("", "Article 225. - Détournement de prêt", article225);
    list.add(data);
    data = new Data("", "Article 226. - Atteinte aux règlements de conditionnement", article226);
    list.add(data);
    data = new Data(titre59, "Article 227. - Incendie et destruction", article227);
    list.add(data);
    data = new Data("", "Article 228. - Activités dangereuses", article228);
    list.add(data);
    data = new Data("", "Article 229. - Substances explosives", article229);
    list.add(data);
    data = new Data("", "Article 229-1. - Déchets toxiques", article229_1);
    list.add(data);
    data = new Data("", "Article 230. - Voies publique", article230);
    list.add(data);
    data = new Data(titre60, "Article 231. - Reunions et manifestations publiques", article231);
    list.add(data);
    data = new Data("", "Article 231-1. - Manifestation a caractère politique au sein d'un établissement public et en milieu educatif", article231_1);
    list.add(data);
    data = new Data("", "Article 232. - Attroupement", article232);
    list.add(data);
    data = new Data("", "Article 233. - Attroupement armés", article233);
    list.add(data);
    data = new Data("", "Article 234. - Déchéances", article234);
    list.add(data);
    data = new Data("", "Article 235. Cris sédicieux", article235);
    list.add(data);
    data = new Data("", "Article 236. - Pillage en bande", article236);
    list.add(data);
    data = new Data("", "Article 237. - Détention et port d'arme", article237);
    list.add(data);
    data = new Data("", "Article 238. - Port dangereux d'une arme", article238);
    list.add(data);
    data = new Data("", "Article 239. - Troubles de jouissance", article239);
    list.add(data);
    data = new Data("", "Article 240. - Fausses nouvelles", article240);
    list.add(data);
    data = new Data("", "Article 241. - Outrage aux races et aux religions", article241);
    list.add(data);
    data = new Data("", "Article 242. - Discrimination", article242);
    list.add(data);
    data = new Data("", "Article 243. - Ivresse publique", article243);
    list.add(data);
    data = new Data("", "Article 244. - Réitération", article244);
    list.add(data);
    data = new Data("", "Article 245. - Mendicité", article245);
    list.add(data);
    data = new Data("", "Article 246. - Mendicité aggravée", article246);
    list.add(data);
    data = new Data("", "Article 247. - Vagabondage", article247);
    list.add(data);
    data = new Data("", "Article 248. - Préparatifs dangereux", article248);
    list.add(data);
    data = new Data("", "Article 249. - Jeux et loteries", article249);
    list.add(data);
    data = new Data("", "Article 249-1. - Non respect des standards et normes de securité, de confort et de salubrité propres au casino", article249_1);
    list.add(data);
    data = new Data("", "Article 249-2. - Violation des prescriptions du cahier des charges attaché au contrat de concession", article249_2);
    list.add(data);
    data = new Data("", "Article 249-3. - Utilisation des equipements non agrees pour casino et jeux en ligne", article249_3);
    list.add(data);
    data = new Data("", "Article 249-4. - Blanchiment d'argent au moyen des jeux et loteries", article249_4);
    list.add(data);
    data = new Data("", "Article 249-5. - Rébellion en matière de jeux et loteries", article249_5);
    list.add(data);
    data = new Data("", "Article 249-6. - Publicité en matière de jeux et loteries", article249_6);
    list.add(data);
    data = new Data("", "Article 249-7. - Accès interdits aux jeux et loteries", article249_7);
    list.add(data);
    data = new Data("", "Article 249-8. - Transaction", article249_8);
    list.add(data);
    data = new Data("", "Article 249-9. - Peines accessoires", article249_9);
    list.add(data);
    data = new Data("", "Article 250. - Maison de prets sur gages", article250);
    list.add(data);
    data = new Data("", "Article 251. - Pratiques de sorcellerie", article251);
    list.add(data);
    data = new Data(titre61, "Article 252. - Faux poids et mesures", article252);
    list.add(data);
    data = new Data("", "Article 253. - Chèque sans provision", article253);
    list.add(data);
    data = new Data("", "Article 254. - Liberté des enchères", article254);
    list.add(data);
    data = new Data("", "Article 255. - Entraves a la liberté du travail", article255);
    list.add(data);
    data = new Data("", "Article 256. - Pression sur les prix", article256);
    list.add(data);
    data = new Data("", "Article 257. - Destruction de denrées", article257);
    list.add(data);
    data = new Data(titre62, "Article 258. - Alteration de denrées alimentaires", article258);
    list.add(data);
    data = new Data("", "Article 258-1. - Vente illicite de médicaments", article258_1);
    list.add(data);
    data = new Data("", "Article 259. - Faux certificat médical", article259);
    list.add(data);
    data = new Data("", "Article 260. - Maladies contagieuses", article260);
    list.add(data);
    data = new Data("", "Article 261. - Pollution", article261);
    list.add(data);
    data = new Data("", "Article 262. - Rupture d'un contrat de travail ou de fourniture", article262);
    list.add(data);
    data = new Data(titre63, "Article 263. - Outrage public a la pudeur", article263);
    list.add(data);
    data = new Data("", "Article 264. - Outrage public aux mœurs", article264);
    list.add(data);
    data = new Data("", "Article 265. - Publications obscènes", article265);
    list.add(data);
    data = new Data("", "Article 266. - Publications eéquivoques", article266);
    list.add(data);
    data = new Data("", "Article 267. - Apologie de certains crimes et délits", article267);
    list.add(data);
    data = new Data("", "Article 268. - Mauvais traitements sur un animal", article268);
    list.add(data);
    data = new Data("", "Article 268-1. - Pratiques sexuelles sur un animal", article268_1);
    list.add(data);
    data = new Data(titre64, "Article 269. - Liberte de conscience", article269);
    list.add(data);
    data = new Data("", "Article 270. - Offense aun ministre du culte", article270);
    list.add(data);
    data = new Data("", "Article 271. - Obstacle a l'exercice d'un ministère", article271);
    list.add(data);
    data = new Data("", "Article 272. - Obstacle aux cultes", article272);
    list.add(data);
    data = new Data("", "Article 273. - Obstacle aux funerailles", article273);
    list.add(data);
    data = new Data("", "Article 274. - Violation de tombeaux et de cadavres", article274);
    list.add(data);
    data = new Data(titre65, "Article 275. - Meurtre", article275);
    list.add(data);
    data = new Data("", "Article 276. - Asassinat", article276);
    list.add(data);
    data = new Data("", "Article 277. - Blessures grave", article277);
    list.add(data);
    data = new Data("", "Article 277-1. - Mutilation génitales", article277_1);
    list.add(data);
    data = new Data("", "Article 277-2. - Atteinte ala croissance d'un organe", article277_2);
    list.add(data);
    data = new Data("", "Article 277-3. - Torture", article277_3);
    list.add(data);
    data = new Data(titre66, "Article 278. - Coups mortels", article278);
    list.add(data);
    data = new Data("", "Article 279. - Coups avec blessures graves", article279);
    list.add(data);
    data = new Data("", "Article 280. - Blessures simples", article280);
    list.add(data);
    data = new Data("", "Article 281. - Blessures légères", article281);
    list.add(data);
    data = new Data("", "Article 282. - Délaissement d'incapable", article282);
    list.add(data);
    data = new Data("", "Article 283. - Omission de porter secours", article283);
    list.add(data);
    data = new Data(titre67, "Article 284. - Erreur sur la victime", article284);
    list.add(data);
    data = new Data("", "Article 285. - Assimilation aux violences", article285);
    list.add(data);
    data = new Data("", "Article 286. - Interventions médicales", article286);
    list.add(data);
    data = new Data("", "Article 287. - Intérêt de la victime", article287);
    list.add(data);
    data = new Data("", "Article 288. - Activités sportives", article288);
    list.add(data);
    data = new Data(titre68, "Article 289. - Homicide et blessures involontaires", article289);
    list.add(data);
    data = new Data("", "Article 290. - Conducteurs de véhicules", article290);
    list.add(data);
    data = new Data(titre69, "Article 291. - Arrestation et séquestration", article291);
    list.add(data);
    data = new Data("", "Article 292. - Travail forcé", article292);
    list.add(data);
    data = new Data("", "Article 293. - Exclavage", article293);
    list.add(data);
    data = new Data("", "Article 294. - Proxemetisme", article294);
    list.add(data);
    data = new Data(titre70, "Article 295. - Outrage privé a la pudeur", article295);
    list.add(data);
    data = new Data("", "Article 296. - Viol", article296);
    list.add(data);
    data = new Data("", "Article 297. - Mariage subséquent", article297);
    list.add(data);
    data = new Data("", "Article 298. - Pénalités aggravées", article298);
    list.add(data);
    data = new Data(titre71, "Article 299. - Violation de domicile", article299);
    list.add(data);
    data = new Data("", "Article 300. - Violation de correspondance", article300);
    list.add(data);
    data = new Data("", "Article 301. - Menaces simples", article301);
    list.add(data);
    data = new Data("", "Article 302. - Menaces sous conditions", article302);
    list.add(data);
    data = new Data("", "Article 302-1. - Harcelement sexuel", article302_1);
    list.add(data);
    data = new Data("", "Article 303. - Chantage", article303);
    list.add(data);
    data = new Data("", "Article 304. - Denonciation calomnieuse", article304);
    list.add(data);
    data = new Data("", "Article 305. - Diffamation", article305);
    list.add(data);
    data = new Data("", "Article 306. - Exceptions ala dlffamation", article306);
    list.add(data);
    data = new Data("", "Article 307. - Injures", article307);
    list.add(data);
    data = new Data("", "Article 308.- Extorsion d'un acte, d'une signature, d'un blanc-seing", article308);
    list.add(data);
    data = new Data(titre72, "Article 309. - Abus de blanc-seing", article309);
    list.add(data);
    data = new Data("", "Article 310. - Violation du secret professionnel", article310);
    list.add(data);
    data = new Data("", "Article 311. - Violation du secret commercial", article311);
    list.add(data);
    data = new Data("", "Article 311-1. - Inobservation des formalites d'inscription au Registre du Commerce et du Credit Mobilier", article311_1);
    list.add(data);
    data = new Data("", "Article 311-2. - Non indication de la qualite de locataire-gerant d'un fonds de commerce", article311_2);
    list.add(data);
    data = new Data("", "Article 311-3. - Inscription frauduleuse d'une surêté mobilière", article311_3);
    list.add(data);
    data = new Data("", "Article 312. - Corruption des agents du secteur privé", article312);
    list.add(data);
    data = new Data("", "Article 313. - Tromperie envers des associés", article313);
    list.add(data);
    data = new Data("", "Article 313-1. - Non déclaration du conflit d'intérêts", article313_1);
    list.add(data);
    data = new Data("", "Article 314. - Faux en écriture privée ou de commerce", article314);
    list.add(data);
    data = new Data("", "Article 314-1. - Défauts comptables, tenue irregulière ou absence de comptabilité", article314_1);
    list.add(data);
    data = new Data("", "Article 315. - Contrefacon de certificat", article315);
    list.add(data);
    data = new Data(titre73, "Article 316. - Destruction", article316);
    list.add(data);
    data = new Data("", "Article 317. - Destruction de bornes ou de clôtures", article317);
    list.add(data);
    data = new Data(titre74, "Article 318. - Vol, abus de confiance, escroquerie", article318);
    list.add(data);
    data = new Data("", "Article 319. - Vol et abus de confiance speciaux", article319);
    list.add(data);
    data = new Data("", "Article 320. - Vol aggravé", article320);
    list.add(data);
    data = new Data("", "Article 321. - Abus de confiance et escroquerie aggravés", article321);
    list.add(data);
    data = new Data("", "Article 322. - Fillouterie", article322);
    list.add(data);
    data = new Data("", "Article 322-1. - Filouteries de loyers", article322_1);
    list.add(data);
    data = new Data("", "Article 322-2. - Deterioration des lieux loués", article322_2);
    list.add(data);
    data = new Data("", "Article 322-3. - Atteinte au privilège du bailleur d'immeuble", article322_3);
    list.add(data);
    data = new Data("", "Article 323. - Immunités", article323);
    list.add(data);
    data = new Data("", "Article 324. - Recel", article324);
    list.add(data);
    data = new Data("", "Article 325. - Usures", article325);
    list.add(data);
    data = new Data("", "Article 326. - Vente prohibées", article326);
    list.add(data);
    data = new Data("", "Article 327. - Atteinte a la proprieté litteraire et artistique", article327);
    list.add(data);
    data = new Data("", "Article 328. - Atteinte au brevet d'invention", article328);
    list.add(data);
    data = new Data("", "Article 329. - Dessins et modèles industriels", article329);
    list.add(data);
    data = new Data("", "Article 330. - Marques de fabrique ou de commerce", article330);
    list.add(data);
    data = new Data(titre75, "Article 331. - Débiteur frauduleux", article331);
    list.add(data);
    data = new Data("", "Article 332. - Banqueroute simple", article332);
    list.add(data);
    data = new Data("", "Article 333. - Banqueroute frauduleuse", article333);
    list.add(data);
    data = new Data("", "Article 334. - Mandataires sociaux", article334);
    list.add(data);
    data = new Data("", "Article 334-1. - Représentants legaux ou de fait", article334_1);
    list.add(data);
    data = new Data("", "Article 334-2. - Personnes physiques dirigeantes et représentants permanents des personnes morales dirigeantes", article334_2);
    list.add(data);
    data = new Data("", "Article 335. - Infractions commises par les tiers", article335);
    list.add(data);
    data = new Data("", "Article 335-1. - Infractions commises par le conjoint, les parents ou les alliés du débiteur", article335_1);
    list.add(data);
    data = new Data("", "Article 335-2. - Dommages-intérêts et reintégration", article335_2);
    list.add(data);
    data = new Data("", "Article 335-3. - Infractions commises par le syndic de procédure collective", article335_3);
    list.add(data);
    data = new Data("", "Article 336. - Avantages illégitlmes d'un creancier", article336);
    list.add(data);
    data = new Data(titre76, "Article 337. - Avortement", article337);
    list.add(data);
    data = new Data("", "Article 338. - Violences sur une femme enceinte", article338);
    list.add(data);
    data = new Data("", "Article 339. - Exception", article339);
    list.add(data);
    data = new Data("", "Article 340. - Infanticide", article340);
    list.add(data);
    data = new Data("", "Article 341. - Atteinte a la filiation", article341);
    list.add(data);
    data = new Data("", "Article 342. - Mise en gage des personnes", article342);
    list.add(data);
    data = new Data("", "Article 342-1. - Trafic et traite des personnes", article342_1);
    list.add(data);
    data = new Data("", "Article 343. - Prostitution", article343);
    list.add(data);
    data = new Data("", "Article 344. - Corruption de la jeunesse", article344);
    list.add(data);
    data = new Data("", "Article 345. - Danger moral", article345);
    list.add(data);
    data = new Data("", "Article 346. - Outrage a la pudeur en presence d'une personne mineure de seize ans", article346);
    list.add(data);
    data = new Data("", "Article 347. - Outrage a la pudeur sur une personne mineure de seize a vingt et un ans", article347);
    list.add(data);
    data = new Data("", "Article 347-1. - Hommosexualité", article347_1);
    list.add(data);
    data = new Data("", "Article 348. - Boissons", article348);
    list.add(data);
    data = new Data("", "Article 349. - Abus de faiblesse d'un mineur", article349);
    list.add(data);
    data = new Data("", "Article 350. - Violences sur enfants", article350);
    list.add(data);
    data = new Data("", "Article 351. - Violences sur ascendants", article351);
    list.add(data);
    data = new Data("", "Article 352. - Enlèvement de mineurs", article352);
    list.add(data);
    data = new Data("", "Article 353. - Enlèvement avec fraude ou violences", article353);
    list.add(data);
    data = new Data("", "Article 354. - Aggravation", article354);
    list.add(data);
    data = new Data("", "Article 355. - Non représentation d'enfant", article355);
    list.add(data);
    data = new Data("", "Article 355-1. - Entrave a l'exercice du droit de visite", article355_1);
    list.add(data);
    data = new Data("", "Article 355-2. - Entrave au droit a la scolarisation", article355_2);
    list.add(data);
    data = new Data("", "Article 356. - Mariage forcé", article356);
    list.add(data);
    data = new Data("", "Article 357. - Exigence abusive d'une dot", article357);
    list.add(data);
    data = new Data("", "Article 358. - Abandon de foyer", article358);
    list.add(data);
    data = new Data("", "Article 358-1. - Expulsion du domicile conjugal", article358_1);
    list.add(data);
    data = new Data("", "Article 359. - Bigami", article359);
    list.add(data);
    data = new Data("", "Article 360. - Isceste", article360);
    list.add(data);
    data = new Data("", "Article 361. - Adultère", article361);
    list.add(data);
    data = new Data(titre77, "Article 362 à 370. - ", article362);
    list.add(data);
    data = new Data(titre78, "Article 371. - ", article371);
    list.add(data);
    data = new Data("", "Article 372. - ", article372);
    list.add(data);
  }

  @Override
  public void onResume() {
    super.onResume();
    mRecyclerAdapter.setListener(this);
    mRecyclerView.setAdapter(mRecyclerAdapter);
  }

  @Override
  public boolean onQueryTextSubmit(String s) {
    return false;
  }

  @Override
  public boolean onQueryTextChange(String newText) {
    final List<Data> filteredModelList = filter(list, newText);
    if (filteredModelList.size() > 0) {
      mRecyclerAdapter.setFilter(filteredModelList);
      mRecyclerAdapter.updateList(filteredModelList, newText);
      return true;
    } else {
      Toast.makeText(CodePenale.this, "Aucun Résultat", Toast.LENGTH_SHORT).show();
      return false;
    }
  }

  // Search Method
  private List<Data> filter(List<Data> models, String query) {
    query = query.toLowerCase();
    this.searchString = query;

    final List<Data> filteredModelList = new ArrayList<>();
    for (Data model : models) {
      final String text = model.getArticle().toLowerCase();
      final String text2 = model.getDescription().toLowerCase();
      if (text.contains(query)) {
        filteredModelList.add(model);
      } else if (text2.contains(query)) {
        filteredModelList.add(model);
      }
    }

    mRecyclerAdapter = new AdapterCodePenale(getApplicationContext(), list);
    mRecyclerView.setLayoutManager(new LinearLayoutManager(CodePenale.this));
    mRecyclerView.setAdapter(mRecyclerAdapter);
    mRecyclerAdapter.notifyDataSetChanged();

    return filteredModelList;
  }

  @Override
  public boolean onCreateOptionsMenu(Menu menu) {
    getMenuInflater().inflate(R.menu.menu_code_penale, menu);

    MenuItem searchitem = menu.findItem(R.id.action_search);

    searchView = (SearchView) MenuItemCompat.getActionView(searchitem);
    SearchManager searchManager = (SearchManager) getSystemService(SEARCH_SERVICE);
    searchView.setSearchableInfo(searchManager.getSearchableInfo(getComponentName()));

    TextView searchText = searchView.findViewById(android.support.v7.appcompat.R.id.search_src_text);

    searchText.setTextColor(Color.parseColor("#FFFFFF"));
    searchText.setHintTextColor(Color.parseColor("#FFFFFF"));
    searchText.setHint("Recherche...");
    if (searchText.isShown()){
      textView.setVisibility(View.GONE);
    }
    searchView.setOnQueryTextListener(this);

    return super.onCreateOptionsMenu(menu);
  }

  @Override
  public boolean onOptionsItemSelected(MenuItem item) {
    return super.onOptionsItemSelected(item);
  }

  @Override
  public void onBackPressed() {
    View view = this.getCurrentFocus();
    if (view != null) {
      InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
      imm.hideSoftInputFromWindow(view.getWindowToken(), 0);
    }
    if (!searchView.isIconified()) {
      searchView.setIconified(true);
    } else {
      startActivity(new Intent(CodePenale.this, RegleDeDroit.class));
      overridePendingTransition(R.anim.anim3, R.anim.anim4);
      finish();
    }
  }
}