package cm.logram.lecitoyen.reglesDeDroits;

import android.annotation.SuppressLint;
import android.app.SearchManager;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.FloatingActionButton;
import android.support.v4.view.MenuItemCompat;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.SearchView;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.inputmethod.InputMethodManager;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

import cm.logram.lecitoyen.R;
import cm.logram.lecitoyen.adapter.AdapterCodeDeJusticeMilitaire.ClickListener;
import cm.logram.lecitoyen.adapter.AdapterCodeElectoral;
import cm.logram.lecitoyen.favoris.FavorisCodeElectoral;
import cm.logram.lecitoyen.model.Data;

@SuppressLint("NewApi")
public class CodeElectoral extends AppCompatActivity implements ClickListener,View.OnClickListener, SearchView.OnQueryTextListener {

  private Toolbar toolbar;
  private FloatingActionButton floatingActionButton;
  private RecyclerView mRecyclerView;
  private AdapterCodeElectoral mRecyclerAdapter;
  private List<Data> list;
  private SharedPreferences mSharedPreferences;
  private String searchString = "";
  private SearchView searchView;
  private TextView textView;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_code_electoral);

    mSharedPreferences = getSharedPreferences("spWords", 0);

    toolbar = findViewById(R.id.toolbar);
    toolbar.setTitle("");
    setSupportActionBar(toolbar);

    textView = findViewById(R.id.en_tête);
    floatingActionButton = findViewById(R.id.fab);
    floatingActionButton.setOnClickListener(this);

    list = new ArrayList<>();
    mRecyclerView = findViewById(R.id.recyclerViewMain);
    mRecyclerAdapter = new AdapterCodeElectoral(getApplicationContext(), list);
    mRecyclerView.setHasFixedSize(true);
    mRecyclerAdapter.setListener(this);
    mRecyclerView.setItemAnimator(new DefaultItemAnimator());
    mRecyclerView.setLayoutManager(new LinearLayoutManager(getApplicationContext()));
    mRecyclerView.setAdapter(mRecyclerAdapter);

    /*Cache le bouton flottant lors du scroll*/
    mRecyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
      @Override
      public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
        if (dy > 0 && floatingActionButton.isShown()) {
          floatingActionButton.hide();
        } else if (dy < 0 && floatingActionButton.getVisibility() != View.VISIBLE) {
          floatingActionButton.show();
        }
      }
    });
    prepareWordsList();
  }

  @Override
  public void onClick(View view) {
    switch (view.getId()) {
      case R.id.fab:
        Intent favList = new Intent(this, FavorisCodeElectoral.class);
        startActivity(favList);
        break;
    }
  }

  @Override
  public void itemClicked(View view, int position) {
  }

  private void prepareWordsList() {

    String titre1ce = getText(R.string.titre1ce).toString();
    String titre2ce = getText(R.string.titre2ce).toString();
    String titre3ce = getText(R.string.titre3ce).toString();
    String titre4ce = getText(R.string.titre4ce).toString();
    String titre5ce = getText(R.string.titre5ce).toString();
    String titre6ce = getText(R.string.titre6ce).toString();
    String titre7ce = getText(R.string.titre7ce).toString();
    String titre8ce = getText(R.string.titre8ce).toString();
    String titre9ce = getText(R.string.titre9ce).toString();
    String titre10ce = getText(R.string.titre10ce).toString();
    String titre11ce = getText(R.string.titre11ce).toString();
    String titre12ce = getText(R.string.titre12ce).toString();
    String titre13ce = getText(R.string.titre13ce).toString();
    String titre14ce = getText(R.string.titre14ce).toString();
    String titre15ce = getText(R.string.titre15ce).toString();
    String titre16ce = getText(R.string.titre16ce).toString();
    String titre17ce = getText(R.string.titre17ce).toString();
    String titre18ce = getText(R.string.titre18ce).toString();
    String titre19ce = getText(R.string.titre19ce).toString();
    String titre20ce = getText(R.string.titre20ce).toString();
    String titre21ce = getText(R.string.titre21ce).toString();
    String titre22ce = getText(R.string.titre22ce).toString();
    String titre23ce = getText(R.string.titre23ce).toString();
    String titre24ce = getText(R.string.titre24ce).toString();
    String titre25ce = getText(R.string.titre25ce).toString();
    String titre26ce = getText(R.string.titre26ce).toString();
    String titre27ce = getText(R.string.titre27ce).toString();
    String titre28ce = getText(R.string.titre28ce).toString();
    String titre29ce = getText(R.string.titre29ce).toString();
    String titre30ce = getText(R.string.titre30ce).toString();
    String titre31ce = getText(R.string.titre31ce).toString();
    String titre32ce = getText(R.string.titre32ce).toString();
    String titre33ce = getText(R.string.titre33ce).toString();
    String titre34ce = getText(R.string.titre34ce).toString();
    String titre35ce = getText(R.string.titre35ce).toString();
    String titre36ce = getText(R.string.titre36ce).toString();
    String titre37ce = getText(R.string.titre37ce).toString();
    String titre38ce = getText(R.string.titre38ce).toString();
    String titre39ce = getText(R.string.titre39ce).toString();
    String titre40ce = getText(R.string.titre40ce).toString();
    String titre41ce = getText(R.string.titre41ce).toString();
    String titre42ce = getText(R.string.titre42ce).toString();
    String titre43ce = getText(R.string.titre43ce).toString();
    String titre44ce = getText(R.string.titre44ce).toString();
    String titre45ce = getText(R.string.titre45ce).toString();
    String titre46ce = getText(R.string.titre46ce).toString();
    String titre47ce = getText(R.string.titre47ce).toString();
    String titre48ce = getText(R.string.titre48ce).toString();
    String titre49ce = getText(R.string.titre49ce).toString();
    String titre50ce = getText(R.string.titre50ce).toString();
    String titre51ce = getText(R.string.titre51ce).toString();
    String titre52ce = getText(R.string.titre52ce).toString();
    String titre53ce = getText(R.string.titre53ce).toString();
    String titre54ce = getText(R.string.titre54ce).toString();
    String titre55ce = getText(R.string.titre55ce).toString();
    String titre56ce = getText(R.string.titre56ce).toString();
    String titre57ce = getText(R.string.titre57ce).toString();
    String titre58ce = getText(R.string.titre58ce).toString();
    String titre59ce = getText(R.string.titre59ce).toString();
    String titre60ce = getText(R.string.titre60ce).toString();
    String titre61ce = getText(R.string.titre61ce).toString();
    String titre62ce = getText(R.string.titre62ce).toString();
    String titre63ce = getText(R.string.titre63ce).toString();
    String titre64ce = getText(R.string.titre64ce).toString();
    String titre65ce = getText(R.string.titre65ce).toString();
    String titre66ce = getText(R.string.titre66ce).toString();
    String titre67ce = getText(R.string.titre67ce).toString();
    String titre68ce = getText(R.string.titre68ce).toString();
    String titre69ce = getText(R.string.titre69ce).toString();
    String titre70ce = getText(R.string.titre70ce).toString();
    String titre71ce = getText(R.string.titre71ce).toString();
    String titre72ce = getText(R.string.titre72ce).toString();
    String titre73ce = getText(R.string.titre73ce).toString();
    String titre74ce = getText(R.string.titre74ce).toString();
    String titre75ce = getText(R.string.titre75ce).toString();
    String titre76ce = getText(R.string.titre76ce).toString();
    String titre77ce = getText(R.string.titre77ce).toString();
    String titre78ce = getText(R.string.titre78ce).toString();
    String titre79ce = getText(R.string.titre79ce).toString();
    String titre80ce = getText(R.string.titre80ce).toString();
    String titre81ce = getText(R.string.titre81ce).toString();
    String titre82ce = getText(R.string.titre82ce).toString();
    String titre83ce = getText(R.string.titre83ce).toString();
    String titre84ce = getText(R.string.titre84ce).toString();
    String titre85ce = getText(R.string.titre85ce).toString();


    String article1 = getText(R.string.article1ce).toString();
    String article2 = getText(R.string.article2ce).toString();
    String article3 = getText(R.string.article3ce).toString();
    String article4 = getText(R.string.article4ce).toString();
    String article5 = getText(R.string.article5ce).toString();
    String article6 = getText(R.string.article6ce).toString();
    String article7 = getText(R.string.article7ce).toString();
    String article8 = getText(R.string.article8ce).toString();
    String article9 = getText(R.string.article9ce).toString();
    String article10 = getText(R.string.article10ce).toString();
    String article11 = getText(R.string.article11ce).toString();
    String article12 = getText(R.string.article12ce).toString();
    String article13 = getText(R.string.article13ce).toString();
    String article14 = getText(R.string.article14ce).toString();
    String article15 = getText(R.string.article15ce).toString();
    String article16 = getText(R.string.article16ce).toString();
    String article17 = getText(R.string.article17ce).toString();
    String article18 = getText(R.string.article18ce).toString();
    String article19 = getText(R.string.article19ce).toString();
    String article20 = getText(R.string.article20ce).toString();
    String article21 = getText(R.string.article21ce).toString();
    String article22 = getText(R.string.article22ce).toString();
    String article23 = getText(R.string.article23ce).toString();
    String article24 = getText(R.string.article24ce).toString();
    String article25 = getText(R.string.article25ce).toString();
    String article26 = getText(R.string.article26ce).toString();
    String article27 = getText(R.string.article27ce).toString();
    String article28 = getText(R.string.article28ce).toString();
    String article29 = getText(R.string.article29ce).toString();
    String article30 = getText(R.string.article30ce).toString();
    String article31 = getText(R.string.article31ce).toString();
    String article32 = getText(R.string.article32ce).toString();
    String article33 = getText(R.string.article33ce).toString();
    String article34 = getText(R.string.article34ce).toString();
    String article35 = getText(R.string.article35ce).toString();
    String article36 = getText(R.string.article36ce).toString();
    String article37 = getText(R.string.article37ce).toString();
    String article38 = getText(R.string.article38ce).toString();
    String article39 = getText(R.string.article39ce).toString();
    String article40 = getText(R.string.article40ce).toString();
    String article41 = getText(R.string.article41ce).toString();
    String article42 = getText(R.string.article42ce).toString();
    String article43 = getText(R.string.article43ce).toString();
    String article44 = getText(R.string.article44ce).toString();
    String article45 = getText(R.string.article45ce).toString();
    String article46 = getText(R.string.article46ce).toString();
    String article47 = getText(R.string.article47ce).toString();
    String article48 = getText(R.string.article48ce).toString();
    String article49 = getText(R.string.article49ce).toString();
    String article50 = getText(R.string.article50ce).toString();
    String article51 = getText(R.string.article51ce).toString();
    String article52 = getText(R.string.article52ce).toString();
    String article53 = getText(R.string.article53ce).toString();
    String article54 = getText(R.string.article54ce).toString();
    String article55 = getText(R.string.article55ce).toString();
    String article56 = getText(R.string.article56ce).toString();
    String article57 = getText(R.string.article57ce).toString();
    String article58 = getText(R.string.article58ce).toString();
    String article59 = getText(R.string.article59ce).toString();
    String article60 = getText(R.string.article60ce).toString();
    String article61 = getText(R.string.article61ce).toString();
    String article62 = getText(R.string.article62ce).toString();
    String article63 = getText(R.string.article63ce).toString();
    String article64 = getText(R.string.article64ce).toString();
    String article65 = getText(R.string.article65ce).toString();
    String article66 = getText(R.string.article66ce).toString();
    String article67 = getText(R.string.article67ce).toString();
    String article68 = getText(R.string.article68ce).toString();
    String article69 = getText(R.string.article69ce).toString();
    String article70 = getText(R.string.article70ce).toString();
    String article71 = getText(R.string.article71ce).toString();
    String article72 = getText(R.string.article72ce).toString();
    String article73 = getText(R.string.article73ce).toString();
    String article74 = getText(R.string.article74ce).toString();
    String article75 = getText(R.string.article75ce).toString();
    String article76 = getText(R.string.article76ce).toString();
    String article77 = getText(R.string.article77ce).toString();
    String article78 = getText(R.string.article78ce).toString();
    String article79 = getText(R.string.article79ce).toString();
    String article80 = getText(R.string.article80ce).toString();
    String article81 = getText(R.string.article81ce).toString();
    String article82 = getText(R.string.article82ce).toString();
    String article83 = getText(R.string.article83ce).toString();
    String article84 = getText(R.string.article84ce).toString();
    String article85 = getText(R.string.article85ce).toString();
    String article86 = getText(R.string.article86ce).toString();
    String article87 = getText(R.string.article87ce).toString();
    String article88 = getText(R.string.article88ce).toString();
    String article89 = getText(R.string.article89ce).toString();
    String article90 = getText(R.string.article90ce).toString();
    String article91 = getText(R.string.article91ce).toString();
    String article92 = getText(R.string.article92ce).toString();
    String article93 = getText(R.string.article93ce).toString();
    String article94 = getText(R.string.article94ce).toString();
    String article95 = getText(R.string.article95ce).toString();
    String article96 = getText(R.string.article96ce).toString();
    String article97 = getText(R.string.article97ce).toString();
    String article98 = getText(R.string.article98ce).toString();
    String article99 = getText(R.string.article99ce).toString();
    String article100 = getText(R.string.article100ce).toString();
    String article101= getText(R.string.article101ce).toString();
    String article102 = getText(R.string.article102ce).toString();
    String article103 = getText(R.string.article103ce).toString();
    String article104 = getText(R.string.article104ce).toString();
    String article105 = getText(R.string.article105ce).toString();
    String article106 = getText(R.string.article106ce).toString();
    String article107 = getText(R.string.article107ce).toString();
    String article108 = getText(R.string.article108ce).toString();
    String article109 = getText(R.string.article109ce).toString();
    String article110 = getText(R.string.article110ce).toString();
    String article111 = getText(R.string.article111ce).toString();
    String article112 = getText(R.string.article112ce).toString();
    String article113 = getText(R.string.article113ce).toString();
    String article114 = getText(R.string.article114ce).toString();
    String article115 = getText(R.string.article115ce).toString();
    String article116 = getText(R.string.article116ce).toString();
    String article117 = getText(R.string.article117ce).toString();
    String article118 = getText(R.string.article118ce).toString();
    String article119 = getText(R.string.article119ce).toString();
    String article120 = getText(R.string.article120ce).toString();
    String article121 = getText(R.string.article121ce).toString();
    String article122 = getText(R.string.article122ce).toString();
    String article123 = getText(R.string.article123ce).toString();
    String article124 = getText(R.string.article124ce).toString();
    String article125 = getText(R.string.article125ce).toString();
    String article126 = getText(R.string.article126ce).toString();
    String article127 = getText(R.string.article127ce).toString();
    String article128 = getText(R.string.article128ce).toString();
    String article129 = getText(R.string.article129ce).toString();
    String article130 = getText(R.string.article130ce).toString();
    String article131 = getText(R.string.article131ce).toString();
    String article132 = getText(R.string.article132ce).toString();
    String article133 = getText(R.string.article133ce).toString();
    String article134 = getText(R.string.article134ce).toString();
    String article135 = getText(R.string.article135ce).toString();
    String article136 = getText(R.string.article136ce).toString();
    String article137 = getText(R.string.article137ce).toString();
    String article138 = getText(R.string.article138ce).toString();
    String article139 = getText(R.string.article139ce).toString();
    String article140 = getText(R.string.article140ce).toString();
    String article141 = getText(R.string.article141ce).toString();
    String article142 = getText(R.string.article142ce).toString();
    String article143 = getText(R.string.article143ce).toString();
    String article144 = getText(R.string.article144ce).toString();
    String article145 = getText(R.string.article145ce).toString();
    String article146 = getText(R.string.article146ce).toString();
    String article147 = getText(R.string.article147ce).toString();
    String article148 = getText(R.string.article148ce).toString();
    String article149 = getText(R.string.article149ce).toString();
    String article150 = getText(R.string.article150ce).toString();
    String article151 = getText(R.string.article151ce).toString();
    String article152 = getText(R.string.article152ce).toString();
    String article153 = getText(R.string.article153ce).toString();
    String article154 = getText(R.string.article154ce).toString();
    String article155 = getText(R.string.article155ce).toString();
    String article156 = getText(R.string.article156ce).toString();
    String article157 = getText(R.string.article157ce).toString();
    String article158 = getText(R.string.article158ce).toString();
    String article159 = getText(R.string.article159ce).toString();
    String article160 = getText(R.string.article160ce).toString();
    String article161 = getText(R.string.article161ce).toString();
    String article162 = getText(R.string.article162ce).toString();
    String article163 = getText(R.string.article163ce).toString();
    String article164 = getText(R.string.article164ce).toString();
    String article165 = getText(R.string.article165ce).toString();
    String article166 = getText(R.string.article166ce).toString();
    String article167 = getText(R.string.article167ce).toString();
    String article168 = getText(R.string.article168ce).toString();
    String article169 = getText(R.string.article169ce).toString();
    String article170 = getText(R.string.article170ce).toString();
    String article171 = getText(R.string.article171ce).toString();
    String article172 = getText(R.string.article172ce).toString();
    String article173 = getText(R.string.article173ce).toString();
    String article174 = getText(R.string.article174ce).toString();
    String article175 = getText(R.string.article175ce).toString();
    String article176 = getText(R.string.article176ce).toString();
    String article177 = getText(R.string.article177ce).toString();
    String article178 = getText(R.string.article178ce).toString();
    String article179 = getText(R.string.article179ce).toString();
    String article180 = getText(R.string.article180ce).toString();
    String article181 = getText(R.string.article181ce).toString();
    String article182 = getText(R.string.article182ce).toString();
    String article183 = getText(R.string.article183ce).toString();
    String article184 = getText(R.string.article184ce).toString();
    String article185 = getText(R.string.article185ce).toString();
    String article186 = getText(R.string.article186ce).toString();
    String article187 = getText(R.string.article187ce).toString();
    String article188 = getText(R.string.article188ce).toString();
    String article189 = getText(R.string.article189ce).toString();
    String article190 = getText(R.string.article190ce).toString();
    String article191 = getText(R.string.article191ce).toString();
    String article192 = getText(R.string.article192ce).toString();
    String article193 = getText(R.string.article193ce).toString();
    String article194 = getText(R.string.article194ce).toString();
    String article195 = getText(R.string.article195ce).toString();
    String article196 = getText(R.string.article196ce).toString();
    String article197 = getText(R.string.article197ce).toString();
    String article198 = getText(R.string.article198ce).toString();
    String article199 = getText(R.string.article199ce).toString();
    String article200 = getText(R.string.article200ce).toString();
    String article201 = getText(R.string.article201ce).toString();
    String article202 = getText(R.string.article202ce).toString();
    String article203 = getText(R.string.article203ce).toString();
    String article204 = getText(R.string.article204ce).toString();
    String article205 = getText(R.string.article205ce).toString();
    String article206 = getText(R.string.article206ce).toString();
    String article207 = getText(R.string.article207ce).toString();
    String article208 = getText(R.string.article208ce).toString();
    String article209 = getText(R.string.article209ce).toString();
    String article210 = getText(R.string.article210ce).toString();
    String article211 = getText(R.string.article211ce).toString();
    String article212 = getText(R.string.article212ce).toString();
    String article213 = getText(R.string.article213ce).toString();
    String article214 = getText(R.string.article214ce).toString();
    String article215 = getText(R.string.article215ce).toString();
    String article216 = getText(R.string.article216ce).toString();
    String article217 = getText(R.string.article217ce).toString();
    String article218 = getText(R.string.article218ce).toString();
    String article219 = getText(R.string.article219ce).toString();
    String article220 = getText(R.string.article220ce).toString();
    String article221 = getText(R.string.article221ce).toString();
    String article222 = getText(R.string.article222ce).toString();
    String article223 = getText(R.string.article223ce).toString();
    String article224 = getText(R.string.article224ce).toString();
    String article225 = getText(R.string.article225ce).toString();
    String article226 = getText(R.string.article226ce).toString();
    String article227 = getText(R.string.article227ce).toString();
    String article228 = getText(R.string.article228ce).toString();
    String article229 = getText(R.string.article229ce).toString();
    String article230 = getText(R.string.article230ce).toString();
    String article231 = getText(R.string.article231ce).toString();
    String article232 = getText(R.string.article232ce).toString();
    String article233 = getText(R.string.article233ce).toString();
    String article234 = getText(R.string.article234ce).toString();
    String article235 = getText(R.string.article235ce).toString();
    String article236 = getText(R.string.article236ce).toString();
    String article237 = getText(R.string.article237ce).toString();
    String article238 = getText(R.string.article238ce).toString();
    String article239 = getText(R.string.article239ce).toString();
    String article240 = getText(R.string.article240ce).toString();
    String article241 = getText(R.string.article241ce).toString();
    String article242 = getText(R.string.article242ce).toString();
    String article243 = getText(R.string.article243ce).toString();
    String article244 = getText(R.string.article244ce).toString();
    String article245 = getText(R.string.article245ce).toString();
    String article246 = getText(R.string.article246ce).toString();
    String article247 = getText(R.string.article247ce).toString();
    String article248 = getText(R.string.article248ce).toString();
    String article249 = getText(R.string.article249ce).toString();
    String article250 = getText(R.string.article250ce).toString();
    String article251 = getText(R.string.article251ce).toString();
    String article252 = getText(R.string.article252ce).toString();
    String article253 = getText(R.string.article253ce).toString();
    String article254 = getText(R.string.article254ce).toString();
    String article255 = getText(R.string.article255ce).toString();
    String article256 = getText(R.string.article256ce).toString();
    String article257 = getText(R.string.article257ce).toString();
    String article258 = getText(R.string.article258ce).toString();
    String article259 = getText(R.string.article259ce).toString();
    String article260 = getText(R.string.article260ce).toString();
    String article261 = getText(R.string.article261ce).toString();
    String article262 = getText(R.string.article262ce).toString();
    String article263 = getText(R.string.article263ce).toString();
    String article264 = getText(R.string.article264ce).toString();
    String article265 = getText(R.string.article265ce).toString();
    String article266 = getText(R.string.article266ce).toString();
    String article267 = getText(R.string.article267ce).toString();
    String article268 = getText(R.string.article268ce).toString();
    String article269 = getText(R.string.article269ce).toString();
    String article270 = getText(R.string.article270ce).toString();
    String article271 = getText(R.string.article271ce).toString();
    String article272 = getText(R.string.article272ce).toString();
    String article273 = getText(R.string.article273ce).toString();
    String article274 = getText(R.string.article274ce).toString();
    String article275 = getText(R.string.article275ce).toString();
    String article276 = getText(R.string.article276ce).toString();
    String article277 = getText(R.string.article277ce).toString();
    String article278 = getText(R.string.article278ce).toString();
    String article279 = getText(R.string.article279ce).toString();
    String article280 = getText(R.string.article280ce).toString();
    String article281 = getText(R.string.article281ce).toString();
    String article282 = getText(R.string.article282ce).toString();
    String article283 = getText(R.string.article283ce).toString();
    String article284 = getText(R.string.article284ce).toString();
    String article285 = getText(R.string.article285ce).toString();
    String article286 = getText(R.string.article286ce).toString();
    String article287 = getText(R.string.article287ce).toString();
    String article288 = getText(R.string.article288ce).toString();
    String article289 = getText(R.string.article289ce).toString();
    String article290 = getText(R.string.article290ce).toString();
    String article291 = getText(R.string.article291ce).toString();
    String article292 = getText(R.string.article292ce).toString();
    String article293 = getText(R.string.article293ce).toString();
    String article294 = getText(R.string.article294ce).toString();
    String article295 = getText(R.string.article295ce).toString();
    String article296 = getText(R.string.article296ce).toString();
    String article297 = getText(R.string.article297ce).toString();
    String article298 = getText(R.string.article298ce).toString();
    String article299 = getText(R.string.article299ce).toString();

    Data data = new Data(titre1ce, "Article 1", article1);
    list.add(data);
    data = new Data("", "Article 2", article2);
    list.add(data);
    data = new Data("", "Article 3", article3);
    list.add(data);
    data = new Data(titre2ce, "Article 4", article4);
    list.add(data);
    data = new Data("", "Article 5", article5);
    list.add(data);
    data = new Data("", "Article 6", article6);
    list.add(data);
    data = new Data(titre3ce, "Article 7", article7);
    list.add(data);
    data = new Data(titre4ce, "Article 8", article8);
    list.add(data);
    data = new Data("", "Article 9", article9);
    list.add(data);
    data = new Data(titre5ce, "Article 10", article10);
    list.add(data);
    data = new Data("", "Article 11", article11);
    list.add(data);
    data = new Data(titre6ce, "Article 12", article12);
    list.add(data);
    data = new Data("", "Article 13", article13);
    list.add(data);
    data = new Data("", "Article 14", article14);
    list.add(data);
    data = new Data("", "Article 15", article15);
    list.add(data);
    data = new Data("", "Article 16", article16);
    list.add(data);
    data = new Data(titre7ce, "Article 17", article17);
    list.add(data);
    data = new Data(titre8ce, "Article 18", article18);
    list.add(data);
    data = new Data("", "Article 19", article19);
    list.add(data);
    data = new Data("", "Article 20", article20);
    list.add(data);
    data = new Data("", "Article 21", article21);
    list.add(data);
    data = new Data(titre9ce, "Article 22", article22);
    list.add(data);
    data = new Data("", "Article 23", article23);
    list.add(data);
    data = new Data(titre10ce, "Article 24", article24);
    list.add(data);
    data = new Data("", "Article 25", article25);
    list.add(data);
    data = new Data(titre11ce, "Article 26", article26);
    list.add(data);
    data = new Data("", "Article 27", article27);
    list.add(data);
    data = new Data(titre12ce, "Article 28", article28);
    list.add(data);
    data = new Data(titre13ce, "Article 29", article29);
    list.add(data);
    data = new Data(titre14ce, "Article 30", article30);
    list.add(data);
    data = new Data(titre15ce, "Article 31", article31);
    list.add(data);
    data = new Data("", "Article 32", article32);
    list.add(data);
    data = new Data("", "Article 33", article33);
    list.add(data);
    data = new Data("", "Article 34", article34);
    list.add(data);
    data = new Data("", "Article 35", article35);
    list.add(data);
    data = new Data("", "Article 36", article36);
    list.add(data);
    data = new Data("", "Article 37", article37);
    list.add(data);
    data = new Data("", "Article 38", article38);
    list.add(data);
    data = new Data("", "Article 39", article39);
    list.add(data);
    data = new Data(titre16ce, "Article 40", article40);
    list.add(data);
    data = new Data("", "Article 41", article41);
    list.add(data);
    data = new Data("", "Article 42", article42);
    list.add(data);
    data = new Data("", "Article 43", article43);
    list.add(data);
    data = new Data("", "Article 44", article44);
    list.add(data);
    data = new Data(titre17ce, "Article 45", article45);
    list.add(data);
    data = new Data("", "Article 46", article46);
    list.add(data);
    data = new Data(titre18ce, "Article 47", article47);
    list.add(data);
    data = new Data("", "Article 48", article48);
    list.add(data);
    data = new Data(titre19ce, "Article 49", article49);
    list.add(data);
    data = new Data(titre20ce, "Article 50", article50);
    list.add(data);
    data = new Data(titre21ce, "Article 51", article51);
    list.add(data);
    data = new Data("", "Article 52", article52);
    list.add(data);
    data = new Data(titre22ce, "Article 53", article53);
    list.add(data);
    data = new Data(titre23ce, "Article 54", article54);
    list.add(data);
    data = new Data("", "Article 55", article55);
    list.add(data);
    data = new Data("", "Article 56", article56);
    list.add(data);
    data = new Data("", "Article 57", article57);
    list.add(data);
    data = new Data("", "Article 58", article58);
    list.add(data);
    data = new Data("", "Article 59", article59);
    list.add(data);
    data = new Data("", "Article 60", article60);
    list.add(data);
    data = new Data("", "Article 61", article61);
    list.add(data);
    data = new Data("", "Article 62", article62);
    list.add(data);
    data = new Data(titre24ce, "Article 63", article63);
    list.add(data);
    data = new Data("", "Article 64", article64);
    list.add(data);
    data = new Data("", "Article 65", article65);
    list.add(data);
    data = new Data("", "Article 66", article66);
    list.add(data);
    data = new Data("", "Article 67", article67);
    list.add(data);
    data = new Data(titre25ce, "Article 68", article68);
    list.add(data);
    data = new Data("", "Article 69", article69);
    list.add(data);
    data = new Data(titre26ce, "Article 70", article70);
    list.add(data);
    data = new Data("", "Article 71", article71);
    list.add(data);
    data = new Data("", "Article 72", article72);
    list.add(data);
    data = new Data("", "Article 73", article73);
    list.add(data);
    data = new Data(titre27ce, "Article 74", article74);
    list.add(data);
    data = new Data("", "Article 75", article75);
    list.add(data);
    data = new Data("", "Article 76", article76);
    list.add(data);
    data = new Data("", "Article 77", article77);
    list.add(data);
    data = new Data("", "Article 78", article78);
    list.add(data);
    data = new Data("", "Article 79", article79);
    list.add(data);
    data = new Data("", "Article 80", article80);
    list.add(data);
    data = new Data("", "Article 81", article81);
    list.add(data);
    data = new Data(titre28ce, "Article 82", article82);
    list.add(data);
    data = new Data("", "Article 83", article83);
    list.add(data);
    data = new Data(titre29ce, "Article 84", article84);
    list.add(data);
    data = new Data("", "Article 85", article85);
    list.add(data);
    data = new Data(titre30ce, "Article 86", article86);
    list.add(data);
    data = new Data(titre31ce, "Article 87", article87);
    list.add(data);
    data = new Data("", "Article 88", article88);
    list.add(data);
    data = new Data("", "Article 89", article89);
    list.add(data);
    data = new Data("", "Article 90", article90);
    list.add(data);
    data = new Data("", "Article 91", article91);
    list.add(data);
    data = new Data("", "Article 92", article92);
    list.add(data);
    data = new Data("", "Article 93", article93);
    list.add(data);
    data = new Data("", "Article 94", article94);
    list.add(data);
    data = new Data("", "Article 95", article95);
    list.add(data);
    data = new Data(titre32ce, "Article 96", article96);
    list.add(data);
    data = new Data("", "Article 97", article97);
    list.add(data);
    data = new Data(titre33ce, "Article 98", article98);
    list.add(data);
    data = new Data("", "Article 99", article99);
    list.add(data);
    data = new Data("", "Article 100", article100);
    list.add(data);
    data = new Data("", "Article 101", article101);
    list.add(data);
    data = new Data("", "Article 102", article102);
    list.add(data);
    data = new Data("", "Article 103", article103);
    list.add(data);
    data = new Data("", "Article 104", article104);
    list.add(data);
    data = new Data("", "Article 105", article105);
    list.add(data);
    data = new Data("", "Article 106", article106);
    list.add(data);
    data = new Data("", "Article 107", article107);
    list.add(data);
    data = new Data(titre34ce, "Article 108", article108);
    list.add(data);
    data = new Data("", "Article 109", article109);
    list.add(data);
    data = new Data("", "Article 110", article110);
    list.add(data);
    data = new Data("", "Article 111", article111);
    list.add(data);
    data = new Data("", "Article 112", article112);
    list.add(data);
    data = new Data("", "Article 113", article113);
    list.add(data);
    data = new Data("", "Article 114", article114);
    list.add(data);
    data = new Data("", "Article 115", article115);
    list.add(data);
    data = new Data(titre35ce, "Article 116", article116);
    list.add(data);
    data = new Data(titre36ce, "Article 117", article117);
    list.add(data);
    data = new Data("", "Article 118", article118);
    list.add(data);
    data = new Data("", "Article 119", article119);
    list.add(data);
    data = new Data(titre37ce, "Article 120", article120);
    list.add(data);
    data = new Data("", "Article 121", article121);
    list.add(data);
    data = new Data("", "Article 122", article122);
    list.add(data);
    data = new Data("", "Article 123", article123);
    list.add(data);
    data = new Data("", "Article 124", article124);
    list.add(data);
    data = new Data("", "Article 125", article125);
    list.add(data);
    data = new Data("", "Article 126", article126);
    list.add(data);
    data = new Data("", "Article 127", article127);
    list.add(data);
    data = new Data("", "Article 128", article128);
    list.add(data);
    data = new Data("", "Article 129", article129);
    list.add(data);
    data = new Data("", "Article 130", article130);
    list.add(data);
    data = new Data("", "Article 131", article131);
    list.add(data);
    data = new Data(titre38ce, "Article 132", article132);
    list.add(data);
    data = new Data("", "Article 133", article133);
    list.add(data);
    data = new Data("", "Article 134", article134);
    list.add(data);
    data = new Data("", "Article 135", article135);
    list.add(data);
    data = new Data("", "Article 136", article136);
    list.add(data);
    data = new Data(titre39ce, "Article 137", article137);
    list.add(data);
    data = new Data("", "Article 138", article138);
    list.add(data);
    data = new Data("", "Article 139", article139);
    list.add(data);
    data = new Data(titre40ce, "Article 140", article140);
    list.add(data);
    data = new Data("", "Article 141", article141);
    list.add(data);
    data = new Data(titre41ce, "Article 142", article142);
    list.add(data);
    data = new Data("", "Article 143", article143);
    list.add(data);
    data = new Data("", "Article 144", article144);
    list.add(data);
    data = new Data("", "Article 145", article145);
    list.add(data);
    data = new Data("", "Article 146", article146);
    list.add(data);
    data = new Data(titre42ce, "Article 147", article147);
    list.add(data);
    data = new Data(titre43ce, "Article 148", article148);
    list.add(data);
    data = new Data("", "Article 149", article149);
    list.add(data);
    data = new Data("", "Article 150", article150);
    list.add(data);
    data = new Data("", "Article 151", article151);
    list.add(data);
    data = new Data("", "Article 152", article152);
    list.add(data);
    data = new Data("", "Article 153", article153);
    list.add(data);
    data = new Data("", "Article 154", article154);
    list.add(data);
    data = new Data("", "Article 155", article155);
    list.add(data);
    data = new Data(titre44ce, "Article 156", article156);
    list.add(data);
    data = new Data("", "Article 157", article157);
    list.add(data);
    data = new Data("", "Article 158", article158);
    list.add(data);
    data = new Data("", "Article 159", article159);
    list.add(data);
    data = new Data("", "Article 160", article160);
    list.add(data);
    data = new Data("", "Article 161", article161);
    list.add(data);
    data = new Data(titre45ce, "Article 162", article162);
    list.add(data);
    data = new Data("", "Article 163", article163);
    list.add(data);
    data = new Data(titre46ce, "Article 164", article164);
    list.add(data);
    data = new Data("", "Article 165", article165);
    list.add(data);
    data = new Data("", "Article 166", article166);
    list.add(data);
    data = new Data("", "Article 167", article167);
    list.add(data);
    data = new Data(titre47ce, "Article 168", article168);
    list.add(data);
    data = new Data(titre48ce, "Article 169", article169);
    list.add(data);
    data = new Data("", "Article 170", article170);
    list.add(data);
    data = new Data("", "Article 171", article171);
    list.add(data);
    data = new Data("", "Article 172", article172);
    list.add(data);
    data = new Data("", "Article 173", article173);
    list.add(data);
    data = new Data("", "Article 174", article174);
    list.add(data);
    data = new Data(titre49ce, "Article 175", article175);
    list.add(data);
    data = new Data("", "Article 176", article176);
    list.add(data);
    data = new Data("", "Article 177", article177);
    list.add(data);
    data = new Data("", "Article 178", article178);
    list.add(data);
    data = new Data("", "Article 179", article179);
    list.add(data);
    data = new Data("", "Article 180", article180);
    list.add(data);
    data = new Data(titre50ce, "Article 181", article181);
    list.add(data);
    data = new Data("", "Article 182", article182);
    list.add(data);
    data = new Data("", "Article 183", article183);
    list.add(data);
    data = new Data("", "Article 184", article184);
    list.add(data);
    data = new Data("", "Article 185", article185);
    list.add(data);
    data = new Data("", "Article 186", article186);
    list.add(data);
    data = new Data("", "Article 187", article187);
    list.add(data);
    data = new Data("", "Article 188", article188);
    list.add(data);
    data = new Data("", "Article 189", article189);
    list.add(data);
    data = new Data("", "Article 190", article190);
    list.add(data);
    data = new Data(titre51ce, "Article 191", article191);
    list.add(data);
    data = new Data("", "Article 192", article192);
    list.add(data);
    data = new Data("", "Article 193", article193);
    list.add(data);
    data = new Data(titre52ce, "Article 194", article194);
    list.add(data);
    data = new Data("", "Article 195", article195);
    list.add(data);
    data = new Data(titre53ce, "Article 196", article196);
    list.add(data);
    data = new Data(titre54ce, "Article 197", article197);
    list.add(data);
    data = new Data("", "Article 198", article198);
    list.add(data);
    data = new Data("", "Article 199", article199);
    list.add(data);
    data = new Data("", "Article 200", article200);
    list.add(data);
    data = new Data(titre55ce, "Article 201", article201);
    list.add(data);
    data = new Data("", "Article 202", article202);
    list.add(data);
    data = new Data("", "Article 203", article203);
    list.add(data);
    data = new Data("", "Article 204", article204);
    list.add(data);
    data = new Data(titre56ce, "Article 205", article205);
    list.add(data);
    data = new Data("", "Article 206", article206);
    list.add(data);
    data = new Data("", "Article 207", article207);
    list.add(data);
    data = new Data("", "Article 208", article208);
    list.add(data);
    data = new Data(titre57ce, "Article 209", article209);
    list.add(data);
    data = new Data("", "Article 210", article210);
    list.add(data);
    data = new Data("", "Article 211", article211);
    list.add(data);
    data = new Data(titre58ce, "Article 212", article212);
    list.add(data);
    data = new Data("", "Article 213", article213);
    list.add(data);
    data = new Data(titre59ce, "Article 214", article214);
    list.add(data);
    data = new Data("", "Article 215", article215);
    list.add(data);
    data = new Data("", "Article 216", article216);
    list.add(data);
    data = new Data(titre60ce, "Article 217", article217);
    list.add(data);
    data = new Data("", "Article 218", article218);
    list.add(data);
    data = new Data("", "Article 219", article219);
    list.add(data);
    data = new Data(titre61ce, "Article 220", article220);
    list.add(data);
    data = new Data("", "Article 221", article221);
    list.add(data);
    data = new Data(titre62ce, "Article 222", article222);
    list.add(data);
    data = new Data(titre63ce, "Article 223", article223);
    list.add(data);
    data = new Data("", "Article 224", article224);
    list.add(data);
    data = new Data(titre64ce, "Article 225", article225);
    list.add(data);
    data = new Data("", "Article 226", article226);
    list.add(data);
    data = new Data(titre65ce, "Article 227", article227);
    list.add(data);
    data = new Data("", "Article 228", article228);
    list.add(data);
    data = new Data("", "Article 229", article229);
    list.add(data);
    data = new Data(titre66ce, "Article 230", article230);
    list.add(data);
    data = new Data("", "Article 231", article231);
    list.add(data);
    data = new Data(titre67ce, "Article 232", article232);
    list.add(data);
    data = new Data(titre68ce, "Article 233", article233);
    list.add(data);
    data = new Data("", "Article 234", article234);
    list.add(data);
    data = new Data(titre69ce, "Article 235", article235);
    list.add(data);
    data = new Data("", "Article 236", article236);
    list.add(data);
    data = new Data("", "Article 237", article237);
    list.add(data);
    data = new Data("", "Article 238", article238);
    list.add(data);
    data = new Data(titre70ce, "Article 239", article239);
    list.add(data);
    data = new Data("", "Article 240", article240);
    list.add(data);
    data = new Data(titre71ce, "Article 241", article241);
    list.add(data);
    data = new Data("", "Article 242", article242);
    list.add(data);
    data = new Data(titre72ce, "Article 243", article243);
    list.add(data);
    data = new Data("", "Article 244", article244);
    list.add(data);
    data = new Data("", "Article 245", article245);
    list.add(data);
    data = new Data("", "Article 246", article246);
    list.add(data);
    data = new Data("", "Article 247", article247);
    list.add(data);
    data = new Data(titre73ce, "Article 248", article248);
    list.add(data);
    data = new Data("", "Article 249", article249);
    list.add(data);
    data = new Data("", "Article 250", article250);
    list.add(data);
    data = new Data(titre74ce, "Article 251", article251);
    list.add(data);
    data = new Data("", "Article 252", article252);
    list.add(data);
    data = new Data("", "Article 253", article253);
    list.add(data);
    data = new Data("", "Article 254", article254);
    list.add(data);
    data = new Data("", "Article 255", article255);
    list.add(data);
    data = new Data("", "Article 256", article256);
    list.add(data);
    data = new Data("", "Article 257", article257);
    list.add(data);
    data = new Data(titre75ce, "Article 258", article258);
    list.add(data);
    data = new Data("", "Article 259", article259);
    list.add(data);
    data = new Data("", "Article 260", article260);
    list.add(data);
    data = new Data(titre76ce, "Article 261", article261);
    list.add(data);
    data = new Data("", "Article 262", article262);
    list.add(data);
    data = new Data(titre77ce, "Article 263", article263);
    list.add(data);
    data = new Data("", "Article 264", article264);
    list.add(data);
    data = new Data("", "Article 265", article265);
    list.add(data);
    data = new Data("", "Article 266", article266);
    list.add(data);
    data = new Data(titre78ce, "Article 267", article267);
    list.add(data);
    data = new Data("", "Article 268", article268);
    list.add(data);
    data = new Data(titre79ce, "Article 269", article269);
    list.add(data);
    data = new Data("", "Article 270", article270);
    list.add(data);
    data = new Data(titre80ce, "Article 271", article271);
    list.add(data);
    data = new Data("", "Article 272", article272);
    list.add(data);
    data = new Data("", "Article 273", article273);
    list.add(data);
    data = new Data("", "Article 274", article274);
    list.add(data);
    data = new Data(titre81ce, "Article 275", article275);
    list.add(data);
    data = new Data("", "Article 276", article276);
    list.add(data);
    data = new Data("", "Article 277", article277);
    list.add(data);
    data = new Data("", "Article 278", article278);
    list.add(data);
    data = new Data(titre82ce, "Article 279", article279);
    list.add(data);
    data = new Data("", "Article 280", article280);
    list.add(data);
    data = new Data("", "Article 281", article281);
    list.add(data);
    data = new Data("", "Article 282", article282);
    list.add(data);
    data = new Data("", "Article 283", article283);
    list.add(data);
    data = new Data(titre83ce, "Article 284", article284);
    list.add(data);
    data = new Data("", "Article 285", article285);
    list.add(data);
    data = new Data("", "Article 286", article286);
    list.add(data);
    data = new Data("", "Article 287", article287);
    list.add(data);
    data = new Data(titre84ce, "Article 288", article288);
    list.add(data);
    data = new Data("", "Article 289", article289);
    list.add(data);
    data = new Data("", "Article 290", article290);
    list.add(data);
    data = new Data("", "Article 291", article291);
    list.add(data);
    data = new Data("", "Article 292", article292);
    list.add(data);
    data = new Data("", "Article 293", article293);
    list.add(data);
    data = new Data(titre85ce, "Article 294", article294);
    list.add(data);
    data = new Data("", "Article 295", article295);
    list.add(data);
    data = new Data("", "Article 296", article296);
    list.add(data);
    data = new Data("", "Article 297", article297);
    list.add(data);
    data = new Data("", "Article 298", article298);
    list.add(data);
    data = new Data("", "Article 299", article299);
    list.add(data);
  }

  @Override
  public void onResume() {
    super.onResume();
    mRecyclerAdapter.setListener(this);
    mRecyclerView.setAdapter(mRecyclerAdapter);
  }

  @Override
  public boolean onQueryTextSubmit(String s) {
    return false;
  }

  @Override
  public boolean onQueryTextChange(String newText) {
    final List<Data> filteredModelList = filter(list, newText);
    if (filteredModelList.size() > 0) {
      mRecyclerAdapter.setFilter(filteredModelList);
      mRecyclerAdapter.updateList(filteredModelList, newText);
      return true;
    } else {
      Toast.makeText(CodeElectoral.this, "Aucun Résultat", Toast.LENGTH_SHORT).show();
      return false;
    }
  }

  // Search Method
  private List<Data> filter(List<Data> models, String query) {
    query = query.toLowerCase();
    this.searchString = query;

    final List<Data> filteredModelList = new ArrayList<>();
    for (Data model : models) {
      final String text = model.getArticle().toLowerCase();
      final String text2 = model.getDescription().toLowerCase();
      if (text.contains(query)) {
        filteredModelList.add(model);
      } else if (text2.contains(query)) {
        filteredModelList.add(model);
      }
    }

    mRecyclerAdapter = new AdapterCodeElectoral(getApplicationContext(), list);
    mRecyclerView.setLayoutManager(new LinearLayoutManager(CodeElectoral.this));
    mRecyclerView.setAdapter(mRecyclerAdapter);
    mRecyclerAdapter.notifyDataSetChanged();

    return filteredModelList;
  }

  @Override
  public boolean onCreateOptionsMenu(Menu menu) {
    getMenuInflater().inflate(R.menu.menu_code_penale, menu);

    MenuItem searchitem = menu.findItem(R.id.action_search);

    searchView = (SearchView) MenuItemCompat.getActionView(searchitem);
    SearchManager searchManager = (SearchManager) getSystemService(SEARCH_SERVICE);
    searchView.setSearchableInfo(searchManager.getSearchableInfo(getComponentName()));

    TextView searchText = searchView.findViewById(android.support.v7.appcompat.R.id.search_src_text);

    searchText.setTextColor(Color.parseColor("#FFFFFF"));
    searchText.setHintTextColor(Color.parseColor("#FFFFFF"));
    searchText.setHint("Recherche...");
    if (searchText.isShown()){
      textView.setVisibility(View.GONE);
    }
    searchView.setOnQueryTextListener(this);

    return super.onCreateOptionsMenu(menu);
  }

  @Override
  public boolean onOptionsItemSelected(MenuItem item) {
    return super.onOptionsItemSelected(item);
  }

  @Override
  public void onBackPressed() {
    View view = this.getCurrentFocus();
    if (view != null) {
      InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
      imm.hideSoftInputFromWindow(view.getWindowToken(), 0);
    }
    if (!searchView.isIconified()) {
      searchView.setIconified(true);
    } else {
      startActivity(new Intent(CodeElectoral.this, RegleDeDroit.class));
      overridePendingTransition(R.anim.anim3, R.anim.anim4);
      finish();
    }
  }
}